# golangci-lint configuration for AAA Service
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - docs
    - scripts
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Kisanlink/aaa-service
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocognit:
    min-complexity: 20
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 120
  maligned:
    suggest-new: true
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Additional recommended linters
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

  disable:
    - deadcode      # deprecated
    - exhaustivestruct # too strict
    - golint        # deprecated
    - ifshort       # deprecated
    - interfacer    # deprecated
    - maligned      # deprecated
    - nosnakecase   # deprecated
    - scopelint     # deprecated
    - structcheck   # deprecated
    - varcheck      # deprecated
    - wsl           # too opinionated

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - gocognit
        - funlen

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    # Exclude gosec for test files
    - path: _test\.go
      linters:
        - gosec

    # Exclude certain gocritic rules that are too strict
    - linters:
        - gocritic
      text: "(unnamedResult|exitAfterDefer)"

  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
