version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Image tag is $IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"aaa-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Writing task definition file...
      - |
        cat task-definition.json | \
        sed "s|ACCOUNT_ID|$AWS_ACCOUNT_ID|g" | \
        sed "s|REGION|$AWS_DEFAULT_REGION|g" | \
        sed "s|ENVIRONMENT|$ENVIRONMENT|g" | \
        sed "s|DB_HOST|$DB_HOST|g" | \
        sed "s|REDIS_HOST|$REDIS_HOST|g" | \
        sed "s|:latest|:$IMAGE_TAG|g" > taskdef.json
      - echo Task definition prepared

artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yml

cache:
  paths:
    - '/root/.cache/**/*'
    - '/go/pkg/mod/**/*'
