version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: aaa-service-db
    environment:
      POSTGRES_USER: aaa_user
      POSTGRES_PASSWORD: aaa_password
      POSTGRES_DB: aaa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aaa_user -d aaa_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 