// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.1
// source: pkg/proto/v2/address.proto

package pbv2

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Address model with Indian address format
type Address struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type   string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // HOME, WORK, OTHER
	// Core Indian address fields aligned with domain model
	House       string `protobuf:"bytes,4,opt,name=house,proto3" json:"house,omitempty"`
	Street      string `protobuf:"bytes,5,opt,name=street,proto3" json:"street,omitempty"`
	Landmark    string `protobuf:"bytes,6,opt,name=landmark,proto3" json:"landmark,omitempty"`
	PostOffice  string `protobuf:"bytes,7,opt,name=post_office,json=postOffice,proto3" json:"post_office,omitempty"`
	Subdistrict string `protobuf:"bytes,8,opt,name=subdistrict,proto3" json:"subdistrict,omitempty"`
	District    string `protobuf:"bytes,9,opt,name=district,proto3" json:"district,omitempty"`
	Vtc         string `protobuf:"bytes,10,opt,name=vtc,proto3" json:"vtc,omitempty"` // Village/Town/City
	State       string `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`
	Country     string `protobuf:"bytes,12,opt,name=country,proto3" json:"country,omitempty"`
	Pincode     string `protobuf:"bytes,13,opt,name=pincode,proto3" json:"pincode,omitempty"`
	FullAddress string `protobuf:"bytes,14,opt,name=full_address,json=fullAddress,proto3" json:"full_address,omitempty"`
	// System fields
	IsPrimary     bool                   `protobuf:"varint,15,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	IsActive      bool                   `protobuf:"varint,16,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,17,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Address) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Address) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Address) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetLandmark() string {
	if x != nil {
		return x.Landmark
	}
	return ""
}

func (x *Address) GetPostOffice() string {
	if x != nil {
		return x.PostOffice
	}
	return ""
}

func (x *Address) GetSubdistrict() string {
	if x != nil {
		return x.Subdistrict
	}
	return ""
}

func (x *Address) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Address) GetVtc() string {
	if x != nil {
		return x.Vtc
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *Address) GetFullAddress() string {
	if x != nil {
		return x.FullAddress
	}
	return ""
}

func (x *Address) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *Address) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Address) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Address) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Address) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Create Address Request with Indian format
type CreateAddressRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type   string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Indian address fields
	House         string            `protobuf:"bytes,3,opt,name=house,proto3" json:"house,omitempty"`
	Street        string            `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	Landmark      string            `protobuf:"bytes,5,opt,name=landmark,proto3" json:"landmark,omitempty"`
	PostOffice    string            `protobuf:"bytes,6,opt,name=post_office,json=postOffice,proto3" json:"post_office,omitempty"`
	Subdistrict   string            `protobuf:"bytes,7,opt,name=subdistrict,proto3" json:"subdistrict,omitempty"`
	District      string            `protobuf:"bytes,8,opt,name=district,proto3" json:"district,omitempty"`
	Vtc           string            `protobuf:"bytes,9,opt,name=vtc,proto3" json:"vtc,omitempty"`
	State         string            `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Country       string            `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	Pincode       string            `protobuf:"bytes,12,opt,name=pincode,proto3" json:"pincode,omitempty"`
	IsPrimary     bool              `protobuf:"varint,13,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAddressRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateAddressRequest) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *CreateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateAddressRequest) GetLandmark() string {
	if x != nil {
		return x.Landmark
	}
	return ""
}

func (x *CreateAddressRequest) GetPostOffice() string {
	if x != nil {
		return x.PostOffice
	}
	return ""
}

func (x *CreateAddressRequest) GetSubdistrict() string {
	if x != nil {
		return x.Subdistrict
	}
	return ""
}

func (x *CreateAddressRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CreateAddressRequest) GetVtc() string {
	if x != nil {
		return x.Vtc
	}
	return ""
}

func (x *CreateAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateAddressRequest) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *CreateAddressRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *CreateAddressRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Create Address Response
type CreateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Address       *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressResponse) Reset() {
	*x = CreateAddressResponse{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressResponse) ProtoMessage() {}

func (x *CreateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressResponse.ProtoReflect.Descriptor instead.
func (*CreateAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAddressResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Get Address Request
type GetAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressRequest) Reset() {
	*x = GetAddressRequest{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressRequest) ProtoMessage() {}

func (x *GetAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{3}
}

func (x *GetAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Get Address Response
type GetAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Address       *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressResponse) Reset() {
	*x = GetAddressResponse{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressResponse) ProtoMessage() {}

func (x *GetAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressResponse.ProtoReflect.Descriptor instead.
func (*GetAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{4}
}

func (x *GetAddressResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Get Addresses By User Request
type GetAddressesByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressesByUserRequest) Reset() {
	*x = GetAddressesByUserRequest{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressesByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressesByUserRequest) ProtoMessage() {}

func (x *GetAddressesByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressesByUserRequest.ProtoReflect.Descriptor instead.
func (*GetAddressesByUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{5}
}

func (x *GetAddressesByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAddressesByUserRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

// Get Addresses By User Response
type GetAddressesByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressesByUserResponse) Reset() {
	*x = GetAddressesByUserResponse{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressesByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressesByUserResponse) ProtoMessage() {}

func (x *GetAddressesByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressesByUserResponse.ProtoReflect.Descriptor instead.
func (*GetAddressesByUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{6}
}

func (x *GetAddressesByUserResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAddressesByUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAddressesByUserResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Update Address Request
type UpdateAddressRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Indian address fields
	House         string            `protobuf:"bytes,3,opt,name=house,proto3" json:"house,omitempty"`
	Street        string            `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	Landmark      string            `protobuf:"bytes,5,opt,name=landmark,proto3" json:"landmark,omitempty"`
	PostOffice    string            `protobuf:"bytes,6,opt,name=post_office,json=postOffice,proto3" json:"post_office,omitempty"`
	Subdistrict   string            `protobuf:"bytes,7,opt,name=subdistrict,proto3" json:"subdistrict,omitempty"`
	District      string            `protobuf:"bytes,8,opt,name=district,proto3" json:"district,omitempty"`
	Vtc           string            `protobuf:"bytes,9,opt,name=vtc,proto3" json:"vtc,omitempty"`
	State         string            `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Country       string            `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	Pincode       string            `protobuf:"bytes,12,opt,name=pincode,proto3" json:"pincode,omitempty"`
	IsPrimary     bool              `protobuf:"varint,13,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	IsActive      bool              `protobuf:"varint,14,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAddressRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateAddressRequest) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *UpdateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *UpdateAddressRequest) GetLandmark() string {
	if x != nil {
		return x.Landmark
	}
	return ""
}

func (x *UpdateAddressRequest) GetPostOffice() string {
	if x != nil {
		return x.PostOffice
	}
	return ""
}

func (x *UpdateAddressRequest) GetSubdistrict() string {
	if x != nil {
		return x.Subdistrict
	}
	return ""
}

func (x *UpdateAddressRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UpdateAddressRequest) GetVtc() string {
	if x != nil {
		return x.Vtc
	}
	return ""
}

func (x *UpdateAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateAddressRequest) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *UpdateAddressRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *UpdateAddressRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateAddressRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Update Address Response
type UpdateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Address       *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressResponse) Reset() {
	*x = UpdateAddressResponse{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressResponse) ProtoMessage() {}

func (x *UpdateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressResponse.ProtoReflect.Descriptor instead.
func (*UpdateAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAddressResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Delete Address Request
type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SoftDelete    bool                   `protobuf:"varint,2,opt,name=soft_delete,json=softDelete,proto3" json:"soft_delete,omitempty"` // If true, mark as inactive instead of deleting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteAddressRequest) GetSoftDelete() bool {
	if x != nil {
		return x.SoftDelete
	}
	return false
}

// Delete Address Response
type DeleteAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressResponse) Reset() {
	*x = DeleteAddressResponse{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressResponse) ProtoMessage() {}

func (x *DeleteAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressResponse.ProtoReflect.Descriptor instead.
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAddressResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// List Addresses Request
type ListAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Filter by user
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                   // Filter by type
	ActiveOnly    bool                   `protobuf:"varint,6,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesRequest) Reset() {
	*x = ListAddressesRequest{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesRequest) ProtoMessage() {}

func (x *ListAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesRequest.ProtoReflect.Descriptor instead.
func (*ListAddressesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{11}
}

func (x *ListAddressesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAddressesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAddressesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListAddressesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAddressesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListAddressesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

// List Addresses Response
type ListAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesResponse) Reset() {
	*x = ListAddressesResponse{}
	mi := &file_pkg_proto_v2_address_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesResponse) ProtoMessage() {}

func (x *ListAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v2_address_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesResponse.ProtoReflect.Descriptor instead.
func (*ListAddressesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v2_address_proto_rawDescGZIP(), []int{12}
}

func (x *ListAddressesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListAddressesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListAddressesResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ListAddressesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListAddressesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAddressesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_pkg_proto_v2_address_proto protoreflect.FileDescriptor

const file_pkg_proto_v2_address_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/proto/v2/address.proto\x12\x05pb.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x05\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05house\x18\x04 \x01(\tR\x05house\x12\x16\n" +
	"\x06street\x18\x05 \x01(\tR\x06street\x12\x1a\n" +
	"\blandmark\x18\x06 \x01(\tR\blandmark\x12\x1f\n" +
	"\vpost_office\x18\a \x01(\tR\n" +
	"postOffice\x12 \n" +
	"\vsubdistrict\x18\b \x01(\tR\vsubdistrict\x12\x1a\n" +
	"\bdistrict\x18\t \x01(\tR\bdistrict\x12\x10\n" +
	"\x03vtc\x18\n" +
	" \x01(\tR\x03vtc\x12\x14\n" +
	"\x05state\x18\v \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\f \x01(\tR\acountry\x12\x18\n" +
	"\apincode\x18\r \x01(\tR\apincode\x12!\n" +
	"\ffull_address\x18\x0e \x01(\tR\vfullAddress\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x0f \x01(\bR\tisPrimary\x12\x1b\n" +
	"\tis_active\x18\x10 \x01(\bR\bisActive\x128\n" +
	"\bmetadata\x18\x11 \x03(\v2\x1c.pb.v2.Address.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x03\n" +
	"\x14CreateAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05house\x18\x03 \x01(\tR\x05house\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x1a\n" +
	"\blandmark\x18\x05 \x01(\tR\blandmark\x12\x1f\n" +
	"\vpost_office\x18\x06 \x01(\tR\n" +
	"postOffice\x12 \n" +
	"\vsubdistrict\x18\a \x01(\tR\vsubdistrict\x12\x1a\n" +
	"\bdistrict\x18\b \x01(\tR\bdistrict\x12\x10\n" +
	"\x03vtc\x18\t \x01(\tR\x03vtc\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\v \x01(\tR\acountry\x12\x18\n" +
	"\apincode\x18\f \x01(\tR\apincode\x12\x1d\n" +
	"\n" +
	"is_primary\x18\r \x01(\bR\tisPrimary\x12E\n" +
	"\bmetadata\x18\x0e \x03(\v2).pb.v2.CreateAddressRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\x15CreateAddressResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\aaddress\x18\x03 \x01(\v2\x0e.pb.v2.AddressR\aaddress\"#\n" +
	"\x11GetAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\x12GetAddressResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\aaddress\x18\x03 \x01(\v2\x0e.pb.v2.AddressR\aaddress\"U\n" +
	"\x19GetAddressesByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\"\x85\x01\n" +
	"\x1aGetAddressesByUserResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\taddresses\x18\x03 \x03(\v2\x0e.pb.v2.AddressR\taddresses\"\xff\x03\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05house\x18\x03 \x01(\tR\x05house\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x1a\n" +
	"\blandmark\x18\x05 \x01(\tR\blandmark\x12\x1f\n" +
	"\vpost_office\x18\x06 \x01(\tR\n" +
	"postOffice\x12 \n" +
	"\vsubdistrict\x18\a \x01(\tR\vsubdistrict\x12\x1a\n" +
	"\bdistrict\x18\b \x01(\tR\bdistrict\x12\x10\n" +
	"\x03vtc\x18\t \x01(\tR\x03vtc\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\v \x01(\tR\acountry\x12\x18\n" +
	"\apincode\x18\f \x01(\tR\apincode\x12\x1d\n" +
	"\n" +
	"is_primary\x18\r \x01(\bR\tisPrimary\x12\x1b\n" +
	"\tis_active\x18\x0e \x01(\bR\bisActive\x12E\n" +
	"\bmetadata\x18\x0f \x03(\v2).pb.v2.UpdateAddressRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\x15UpdateAddressResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\aaddress\x18\x03 \x01(\v2\x0e.pb.v2.AddressR\aaddress\"G\n" +
	"\x14DeleteAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsoft_delete\x18\x02 \x01(\bR\n" +
	"softDelete\"R\n" +
	"\x15DeleteAddressResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xad\x01\n" +
	"\x14ListAddressesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1f\n" +
	"\vactive_only\x18\x06 \x01(\bR\n" +
	"activeOnly\"\xd2\x01\n" +
	"\x15ListAddressesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\taddresses\x18\x03 \x03(\v2\x0e.pb.v2.AddressR\taddresses\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize2\xde\x03\n" +
	"\x0eAddressService\x12J\n" +
	"\rCreateAddress\x12\x1b.pb.v2.CreateAddressRequest\x1a\x1c.pb.v2.CreateAddressResponse\x12A\n" +
	"\n" +
	"GetAddress\x12\x18.pb.v2.GetAddressRequest\x1a\x19.pb.v2.GetAddressResponse\x12Y\n" +
	"\x12GetAddressesByUser\x12 .pb.v2.GetAddressesByUserRequest\x1a!.pb.v2.GetAddressesByUserResponse\x12J\n" +
	"\rUpdateAddress\x12\x1b.pb.v2.UpdateAddressRequest\x1a\x1c.pb.v2.UpdateAddressResponse\x12J\n" +
	"\rDeleteAddress\x12\x1b.pb.v2.DeleteAddressRequest\x1a\x1c.pb.v2.DeleteAddressResponse\x12J\n" +
	"\rListAddresses\x12\x1b.pb.v2.ListAddressesRequest\x1a\x1c.pb.v2.ListAddressesResponseB7Z5github.com/Kisanlink/aaa-service/v2/pkg/proto/v2;pbv2b\x06proto3"

var (
	file_pkg_proto_v2_address_proto_rawDescOnce sync.Once
	file_pkg_proto_v2_address_proto_rawDescData []byte
)

func file_pkg_proto_v2_address_proto_rawDescGZIP() []byte {
	file_pkg_proto_v2_address_proto_rawDescOnce.Do(func() {
		file_pkg_proto_v2_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_v2_address_proto_rawDesc), len(file_pkg_proto_v2_address_proto_rawDesc)))
	})
	return file_pkg_proto_v2_address_proto_rawDescData
}

var file_pkg_proto_v2_address_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_proto_v2_address_proto_goTypes = []any{
	(*Address)(nil),                    // 0: pb.v2.Address
	(*CreateAddressRequest)(nil),       // 1: pb.v2.CreateAddressRequest
	(*CreateAddressResponse)(nil),      // 2: pb.v2.CreateAddressResponse
	(*GetAddressRequest)(nil),          // 3: pb.v2.GetAddressRequest
	(*GetAddressResponse)(nil),         // 4: pb.v2.GetAddressResponse
	(*GetAddressesByUserRequest)(nil),  // 5: pb.v2.GetAddressesByUserRequest
	(*GetAddressesByUserResponse)(nil), // 6: pb.v2.GetAddressesByUserResponse
	(*UpdateAddressRequest)(nil),       // 7: pb.v2.UpdateAddressRequest
	(*UpdateAddressResponse)(nil),      // 8: pb.v2.UpdateAddressResponse
	(*DeleteAddressRequest)(nil),       // 9: pb.v2.DeleteAddressRequest
	(*DeleteAddressResponse)(nil),      // 10: pb.v2.DeleteAddressResponse
	(*ListAddressesRequest)(nil),       // 11: pb.v2.ListAddressesRequest
	(*ListAddressesResponse)(nil),      // 12: pb.v2.ListAddressesResponse
	nil,                                // 13: pb.v2.Address.MetadataEntry
	nil,                                // 14: pb.v2.CreateAddressRequest.MetadataEntry
	nil,                                // 15: pb.v2.UpdateAddressRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
}
var file_pkg_proto_v2_address_proto_depIdxs = []int32{
	13, // 0: pb.v2.Address.metadata:type_name -> pb.v2.Address.MetadataEntry
	16, // 1: pb.v2.Address.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: pb.v2.Address.updated_at:type_name -> google.protobuf.Timestamp
	14, // 3: pb.v2.CreateAddressRequest.metadata:type_name -> pb.v2.CreateAddressRequest.MetadataEntry
	0,  // 4: pb.v2.CreateAddressResponse.address:type_name -> pb.v2.Address
	0,  // 5: pb.v2.GetAddressResponse.address:type_name -> pb.v2.Address
	0,  // 6: pb.v2.GetAddressesByUserResponse.addresses:type_name -> pb.v2.Address
	15, // 7: pb.v2.UpdateAddressRequest.metadata:type_name -> pb.v2.UpdateAddressRequest.MetadataEntry
	0,  // 8: pb.v2.UpdateAddressResponse.address:type_name -> pb.v2.Address
	0,  // 9: pb.v2.ListAddressesResponse.addresses:type_name -> pb.v2.Address
	1,  // 10: pb.v2.AddressService.CreateAddress:input_type -> pb.v2.CreateAddressRequest
	3,  // 11: pb.v2.AddressService.GetAddress:input_type -> pb.v2.GetAddressRequest
	5,  // 12: pb.v2.AddressService.GetAddressesByUser:input_type -> pb.v2.GetAddressesByUserRequest
	7,  // 13: pb.v2.AddressService.UpdateAddress:input_type -> pb.v2.UpdateAddressRequest
	9,  // 14: pb.v2.AddressService.DeleteAddress:input_type -> pb.v2.DeleteAddressRequest
	11, // 15: pb.v2.AddressService.ListAddresses:input_type -> pb.v2.ListAddressesRequest
	2,  // 16: pb.v2.AddressService.CreateAddress:output_type -> pb.v2.CreateAddressResponse
	4,  // 17: pb.v2.AddressService.GetAddress:output_type -> pb.v2.GetAddressResponse
	6,  // 18: pb.v2.AddressService.GetAddressesByUser:output_type -> pb.v2.GetAddressesByUserResponse
	8,  // 19: pb.v2.AddressService.UpdateAddress:output_type -> pb.v2.UpdateAddressResponse
	10, // 20: pb.v2.AddressService.DeleteAddress:output_type -> pb.v2.DeleteAddressResponse
	12, // 21: pb.v2.AddressService.ListAddresses:output_type -> pb.v2.ListAddressesResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_proto_v2_address_proto_init() }
func file_pkg_proto_v2_address_proto_init() {
	if File_pkg_proto_v2_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_v2_address_proto_rawDesc), len(file_pkg_proto_v2_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_v2_address_proto_goTypes,
		DependencyIndexes: file_pkg_proto_v2_address_proto_depIdxs,
		MessageInfos:      file_pkg_proto_v2_address_proto_msgTypes,
	}.Build()
	File_pkg_proto_v2_address_proto = out.File
	file_pkg_proto_v2_address_proto_goTypes = nil
	file_pkg_proto_v2_address_proto_depIdxs = nil
}
