// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: aaa_client.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client Configuration for connecting to AAA Service
type AAAClientConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceAddress    string                 `protobuf:"bytes,1,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"`                                          // gRPC server address (e.g., "localhost:50051")
	UseTls            bool                   `protobuf:"varint,2,opt,name=use_tls,json=useTls,proto3" json:"use_tls,omitempty"`                                                                 // Enable TLS connection
	TlsCertPath       string                 `protobuf:"bytes,3,opt,name=tls_cert_path,json=tlsCertPath,proto3" json:"tls_cert_path,omitempty"`                                                 // Path to TLS certificate
	TlsKeyPath        string                 `protobuf:"bytes,4,opt,name=tls_key_path,json=tlsKeyPath,proto3" json:"tls_key_path,omitempty"`                                                    // Path to TLS private key
	TlsCaCertPath     string                 `protobuf:"bytes,5,opt,name=tls_ca_cert_path,json=tlsCaCertPath,proto3" json:"tls_ca_cert_path,omitempty"`                                         // Path to CA certificate
	TimeoutSeconds    int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                                         // Request timeout in seconds
	MaxRetryAttempts  int32                  `protobuf:"varint,7,opt,name=max_retry_attempts,json=maxRetryAttempts,proto3" json:"max_retry_attempts,omitempty"`                                 // Maximum retry attempts
	EnableCompression bool                   `protobuf:"varint,8,opt,name=enable_compression,json=enableCompression,proto3" json:"enable_compression,omitempty"`                                // Enable gRPC compression
	ApiKey            string                 `protobuf:"bytes,9,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                                                                  // API key for authentication
	Metadata          map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata headers
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AAAClientConfig) Reset() {
	*x = AAAClientConfig{}
	mi := &file_aaa_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AAAClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AAAClientConfig) ProtoMessage() {}

func (x *AAAClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AAAClientConfig.ProtoReflect.Descriptor instead.
func (*AAAClientConfig) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{0}
}

func (x *AAAClientConfig) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

func (x *AAAClientConfig) GetUseTls() bool {
	if x != nil {
		return x.UseTls
	}
	return false
}

func (x *AAAClientConfig) GetTlsCertPath() string {
	if x != nil {
		return x.TlsCertPath
	}
	return ""
}

func (x *AAAClientConfig) GetTlsKeyPath() string {
	if x != nil {
		return x.TlsKeyPath
	}
	return ""
}

func (x *AAAClientConfig) GetTlsCaCertPath() string {
	if x != nil {
		return x.TlsCaCertPath
	}
	return ""
}

func (x *AAAClientConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *AAAClientConfig) GetMaxRetryAttempts() int32 {
	if x != nil {
		return x.MaxRetryAttempts
	}
	return 0
}

func (x *AAAClientConfig) GetEnableCompression() bool {
	if x != nil {
		return x.EnableCompression
	}
	return false
}

func (x *AAAClientConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AAAClientConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Client Connection Status
type ClientConnectionStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsConnected      bool                   `protobuf:"varint,1,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "connected", "disconnected", "connecting", "error"
	LastConnected    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_connected,json=lastConnected,proto3" json:"last_connected,omitempty"`
	LastHeartbeat    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	ActiveRequests   int32                  `protobuf:"varint,5,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	TotalRequests    int64                  `protobuf:"varint,6,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	FailedRequests   int64                  `protobuf:"varint,7,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AverageLatencyMs float64                `protobuf:"fixed64,9,opt,name=average_latency_ms,json=averageLatencyMs,proto3" json:"average_latency_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientConnectionStatus) Reset() {
	*x = ClientConnectionStatus{}
	mi := &file_aaa_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnectionStatus) ProtoMessage() {}

func (x *ClientConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnectionStatus.ProtoReflect.Descriptor instead.
func (*ClientConnectionStatus) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConnectionStatus) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *ClientConnectionStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClientConnectionStatus) GetLastConnected() *timestamppb.Timestamp {
	if x != nil {
		return x.LastConnected
	}
	return nil
}

func (x *ClientConnectionStatus) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *ClientConnectionStatus) GetActiveRequests() int32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *ClientConnectionStatus) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ClientConnectionStatus) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *ClientConnectionStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ClientConnectionStatus) GetAverageLatencyMs() float64 {
	if x != nil {
		return x.AverageLatencyMs
	}
	return 0
}

// Client Health Check Request
type ClientHealthCheckRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IncludeServerInfo bool                   `protobuf:"varint,1,opt,name=include_server_info,json=includeServerInfo,proto3" json:"include_server_info,omitempty"`
	IncludeMetrics    bool                   `protobuf:"varint,2,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientHealthCheckRequest) Reset() {
	*x = ClientHealthCheckRequest{}
	mi := &file_aaa_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHealthCheckRequest) ProtoMessage() {}

func (x *ClientHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*ClientHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHealthCheckRequest) GetIncludeServerInfo() bool {
	if x != nil {
		return x.IncludeServerInfo
	}
	return false
}

func (x *ClientHealthCheckRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

// Client Health Check Response
type ClientHealthCheckResponse struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	ConnectionStatus *ClientConnectionStatus `protobuf:"bytes,1,opt,name=connection_status,json=connectionStatus,proto3" json:"connection_status,omitempty"`
	ServerHealth     *HealthCheckResponse    `protobuf:"bytes,2,opt,name=server_health,json=serverHealth,proto3" json:"server_health,omitempty"`
	CheckedAt        *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientHealthCheckResponse) Reset() {
	*x = ClientHealthCheckResponse{}
	mi := &file_aaa_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHealthCheckResponse) ProtoMessage() {}

func (x *ClientHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*ClientHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{3}
}

func (x *ClientHealthCheckResponse) GetConnectionStatus() *ClientConnectionStatus {
	if x != nil {
		return x.ConnectionStatus
	}
	return nil
}

func (x *ClientHealthCheckResponse) GetServerHealth() *HealthCheckResponse {
	if x != nil {
		return x.ServerHealth
	}
	return nil
}

func (x *ClientHealthCheckResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

// Batch Request wrapper for efficient bulk operations
type BatchRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestIds         []string               `protobuf:"bytes,1,rep,name=request_ids,json=requestIds,proto3" json:"request_ids,omitempty"`
	SerializedRequests [][]byte               `protobuf:"bytes,2,rep,name=serialized_requests,json=serializedRequests,proto3" json:"serialized_requests,omitempty"` // Serialized individual requests
	BatchSize          int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchId            string                 `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	FailFast           bool                   `protobuf:"varint,5,opt,name=fail_fast,json=failFast,proto3" json:"fail_fast,omitempty"` // Stop processing on first error
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_aaa_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{4}
}

func (x *BatchRequest) GetRequestIds() []string {
	if x != nil {
		return x.RequestIds
	}
	return nil
}

func (x *BatchRequest) GetSerializedRequests() [][]byte {
	if x != nil {
		return x.SerializedRequests
	}
	return nil
}

func (x *BatchRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *BatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchRequest) GetFailFast() bool {
	if x != nil {
		return x.FailFast
	}
	return false
}

// Batch Response wrapper
type BatchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BatchId          string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Responses        []*BatchItemResponse   `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	SuccessCount     int32                  `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount     int32                  `protobuf:"varint,4,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_aaa_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{5}
}

func (x *BatchResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchResponse) GetResponses() []*BatchItemResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BatchResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Individual batch item response
type BatchItemResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success            bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	SerializedResponse []byte                 `protobuf:"bytes,3,opt,name=serialized_response,json=serializedResponse,proto3" json:"serialized_response,omitempty"` // Serialized individual response
	ErrorMessage       string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StatusCode         int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchItemResponse) Reset() {
	*x = BatchItemResponse{}
	mi := &file_aaa_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchItemResponse) ProtoMessage() {}

func (x *BatchItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchItemResponse.ProtoReflect.Descriptor instead.
func (*BatchItemResponse) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{6}
}

func (x *BatchItemResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BatchItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchItemResponse) GetSerializedResponse() []byte {
	if x != nil {
		return x.SerializedResponse
	}
	return nil
}

func (x *BatchItemResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BatchItemResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

// Client Authentication Context
type ClientAuthContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken    string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=token_expires_at,json=tokenExpiresAt,proto3" json:"token_expires_at,omitempty"`
	UserId          string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId  string                 `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Permissions     []string               `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	SessionMetadata map[string]string      `protobuf:"bytes,7,rep,name=session_metadata,json=sessionMetadata,proto3" json:"session_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientAuthContext) Reset() {
	*x = ClientAuthContext{}
	mi := &file_aaa_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthContext) ProtoMessage() {}

func (x *ClientAuthContext) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthContext.ProtoReflect.Descriptor instead.
func (*ClientAuthContext) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{7}
}

func (x *ClientAuthContext) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ClientAuthContext) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ClientAuthContext) GetTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TokenExpiresAt
	}
	return nil
}

func (x *ClientAuthContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClientAuthContext) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ClientAuthContext) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ClientAuthContext) GetSessionMetadata() map[string]string {
	if x != nil {
		return x.SessionMetadata
	}
	return nil
}

// Client Session Management
type ClientSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AuthContext   *ClientAuthContext     `protobuf:"bytes,2,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSession) Reset() {
	*x = ClientSession{}
	mi := &file_aaa_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSession) ProtoMessage() {}

func (x *ClientSession) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSession.ProtoReflect.Descriptor instead.
func (*ClientSession) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{8}
}

func (x *ClientSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientSession) GetAuthContext() *ClientAuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *ClientSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ClientSession) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

func (x *ClientSession) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// Refresh Client Session Request
type RefreshClientSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshClientSessionRequest) Reset() {
	*x = RefreshClientSessionRequest{}
	mi := &file_aaa_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshClientSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshClientSessionRequest) ProtoMessage() {}

func (x *RefreshClientSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshClientSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshClientSessionRequest) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshClientSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RefreshClientSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Refresh Client Session Response
type RefreshClientSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Session       *ClientSession         `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	UpdatedAuth   *ClientAuthContext     `protobuf:"bytes,4,opt,name=updated_auth,json=updatedAuth,proto3" json:"updated_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshClientSessionResponse) Reset() {
	*x = RefreshClientSessionResponse{}
	mi := &file_aaa_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshClientSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshClientSessionResponse) ProtoMessage() {}

func (x *RefreshClientSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshClientSessionResponse.ProtoReflect.Descriptor instead.
func (*RefreshClientSessionResponse) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshClientSessionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RefreshClientSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RefreshClientSessionResponse) GetSession() *ClientSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *RefreshClientSessionResponse) GetUpdatedAuth() *ClientAuthContext {
	if x != nil {
		return x.UpdatedAuth
	}
	return nil
}

// Client Request Tracing
type ClientRequestTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  string                 `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	OperationName string                 `protobuf:"bytes,4,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Logs          []string               `protobuf:"bytes,9,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequestTrace) Reset() {
	*x = ClientRequestTrace{}
	mi := &file_aaa_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequestTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequestTrace) ProtoMessage() {}

func (x *ClientRequestTrace) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequestTrace.ProtoReflect.Descriptor instead.
func (*ClientRequestTrace) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{11}
}

func (x *ClientRequestTrace) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ClientRequestTrace) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *ClientRequestTrace) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *ClientRequestTrace) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *ClientRequestTrace) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ClientRequestTrace) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ClientRequestTrace) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ClientRequestTrace) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ClientRequestTrace) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

// Client Metrics
type ClientMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests      int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessfulRequests int64                  `protobuf:"varint,2,opt,name=successful_requests,json=successfulRequests,proto3" json:"successful_requests,omitempty"`
	FailedRequests     int64                  `protobuf:"varint,3,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	SuccessRate        float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AverageLatencyMs   float64                `protobuf:"fixed64,5,opt,name=average_latency_ms,json=averageLatencyMs,proto3" json:"average_latency_ms,omitempty"`
	P50LatencyMs       float64                `protobuf:"fixed64,6,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P95LatencyMs       float64                `protobuf:"fixed64,7,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs       float64                `protobuf:"fixed64,8,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	ActiveConnections  int32                  `protobuf:"varint,9,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	MetricsCollectedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=metrics_collected_at,json=metricsCollectedAt,proto3" json:"metrics_collected_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientMetrics) Reset() {
	*x = ClientMetrics{}
	mi := &file_aaa_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMetrics) ProtoMessage() {}

func (x *ClientMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMetrics.ProtoReflect.Descriptor instead.
func (*ClientMetrics) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{12}
}

func (x *ClientMetrics) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ClientMetrics) GetSuccessfulRequests() int64 {
	if x != nil {
		return x.SuccessfulRequests
	}
	return 0
}

func (x *ClientMetrics) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *ClientMetrics) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ClientMetrics) GetAverageLatencyMs() float64 {
	if x != nil {
		return x.AverageLatencyMs
	}
	return 0
}

func (x *ClientMetrics) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *ClientMetrics) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *ClientMetrics) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *ClientMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ClientMetrics) GetMetricsCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MetricsCollectedAt
	}
	return nil
}

// Get Client Metrics Request
type GetClientMetricsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResetAfterRead bool                   `protobuf:"varint,1,opt,name=reset_after_read,json=resetAfterRead,proto3" json:"reset_after_read,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetClientMetricsRequest) Reset() {
	*x = GetClientMetricsRequest{}
	mi := &file_aaa_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientMetricsRequest) ProtoMessage() {}

func (x *GetClientMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetClientMetricsRequest) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{13}
}

func (x *GetClientMetricsRequest) GetResetAfterRead() bool {
	if x != nil {
		return x.ResetAfterRead
	}
	return false
}

func (x *GetClientMetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetClientMetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// Get Client Metrics Response
type GetClientMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Metrics       *ClientMetrics         `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientMetricsResponse) Reset() {
	*x = GetClientMetricsResponse{}
	mi := &file_aaa_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientMetricsResponse) ProtoMessage() {}

func (x *GetClientMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aaa_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetClientMetricsResponse) Descriptor() ([]byte, []int) {
	return file_aaa_client_proto_rawDescGZIP(), []int{14}
}

func (x *GetClientMetricsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetClientMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetClientMetricsResponse) GetMetrics() *ClientMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_aaa_client_proto protoreflect.FileDescriptor

const file_aaa_client_proto_rawDesc = "" +
	"\n" +
	"\x10aaa_client.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11aaa_service.proto\"\xdd\x03\n" +
	"\x0fAAAClientConfig\x12'\n" +
	"\x0fservice_address\x18\x01 \x01(\tR\x0eserviceAddress\x12\x17\n" +
	"\ause_tls\x18\x02 \x01(\bR\x06useTls\x12\"\n" +
	"\rtls_cert_path\x18\x03 \x01(\tR\vtlsCertPath\x12 \n" +
	"\ftls_key_path\x18\x04 \x01(\tR\n" +
	"tlsKeyPath\x12'\n" +
	"\x10tls_ca_cert_path\x18\x05 \x01(\tR\rtlsCaCertPath\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12,\n" +
	"\x12max_retry_attempts\x18\a \x01(\x05R\x10maxRetryAttempts\x12-\n" +
	"\x12enable_compression\x18\b \x01(\bR\x11enableCompression\x12\x17\n" +
	"\aapi_key\x18\t \x01(\tR\x06apiKey\x12=\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2!.pb.AAAClientConfig.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x03\n" +
	"\x16ClientConnectionStatus\x12!\n" +
	"\fis_connected\x18\x01 \x01(\bR\visConnected\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12A\n" +
	"\x0elast_connected\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlastConnected\x12A\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12'\n" +
	"\x0factive_requests\x18\x05 \x01(\x05R\x0eactiveRequests\x12%\n" +
	"\x0etotal_requests\x18\x06 \x01(\x03R\rtotalRequests\x12'\n" +
	"\x0ffailed_requests\x18\a \x01(\x03R\x0efailedRequests\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12,\n" +
	"\x12average_latency_ms\x18\t \x01(\x01R\x10averageLatencyMs\"s\n" +
	"\x18ClientHealthCheckRequest\x12.\n" +
	"\x13include_server_info\x18\x01 \x01(\bR\x11includeServerInfo\x12'\n" +
	"\x0finclude_metrics\x18\x02 \x01(\bR\x0eincludeMetrics\"\xdd\x01\n" +
	"\x19ClientHealthCheckResponse\x12G\n" +
	"\x11connection_status\x18\x01 \x01(\v2\x1a.pb.ClientConnectionStatusR\x10connectionStatus\x12<\n" +
	"\rserver_health\x18\x02 \x01(\v2\x17.pb.HealthCheckResponseR\fserverHealth\x129\n" +
	"\n" +
	"checked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"\xb7\x01\n" +
	"\fBatchRequest\x12\x1f\n" +
	"\vrequest_ids\x18\x01 \x03(\tR\n" +
	"requestIds\x12/\n" +
	"\x13serialized_requests\x18\x02 \x03(\fR\x12serializedRequests\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\tR\abatchId\x12\x1b\n" +
	"\tfail_fast\x18\x05 \x01(\bR\bfailFast\"\xd7\x01\n" +
	"\rBatchResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x123\n" +
	"\tresponses\x18\x02 \x03(\v2\x15.pb.BatchItemResponseR\tresponses\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x04 \x01(\x05R\ffailureCount\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x03R\x10processingTimeMs\"\xc3\x01\n" +
	"\x11BatchItemResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12/\n" +
	"\x13serialized_response\x18\x03 \x01(\fR\x12serializedResponse\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\"\xa0\x03\n" +
	"\x11ClientAuthContext\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12D\n" +
	"\x10token_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0etokenExpiresAt\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissions\x12U\n" +
	"\x10session_metadata\x18\a \x03(\v2*.pb.ClientAuthContext.SessionMetadataEntryR\x0fsessionMetadata\x1aB\n" +
	"\x14SessionMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\rClientSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\fauth_context\x18\x02 \x01(\v2\x15.pb.ClientAuthContextR\vauthContext\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\rlast_activity\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"a\n" +
	"\x1bRefreshClientSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\xc0\x01\n" +
	"\x1cRefreshClientSessionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\asession\x18\x03 \x01(\v2\x11.pb.ClientSessionR\asession\x128\n" +
	"\fupdated_auth\x18\x04 \x01(\v2\x15.pb.ClientAuthContextR\vupdatedAuth\"\xab\x03\n" +
	"\x12ClientRequestTrace\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12%\n" +
	"\x0eoperation_name\x18\x04 \x01(\tR\roperationName\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x124\n" +
	"\x04tags\x18\b \x03(\v2 .pb.ClientRequestTrace.TagsEntryR\x04tags\x12\x12\n" +
	"\x04logs\x18\t \x03(\tR\x04logs\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x03\n" +
	"\rClientMetrics\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12/\n" +
	"\x13successful_requests\x18\x02 \x01(\x03R\x12successfulRequests\x12'\n" +
	"\x0ffailed_requests\x18\x03 \x01(\x03R\x0efailedRequests\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12,\n" +
	"\x12average_latency_ms\x18\x05 \x01(\x01R\x10averageLatencyMs\x12$\n" +
	"\x0ep50_latency_ms\x18\x06 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\a \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\b \x01(\x01R\fp99LatencyMs\x12-\n" +
	"\x12active_connections\x18\t \x01(\x05R\x11activeConnections\x12L\n" +
	"\x14metrics_collected_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x12metricsCollectedAt\"\xb5\x01\n" +
	"\x17GetClientMetricsRequest\x12(\n" +
	"\x10reset_after_read\x18\x01 \x01(\bR\x0eresetAfterRead\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\x82\x01\n" +
	"\x18GetClientMetricsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\ametrics\x18\x03 \x01(\v2\x11.pb.ClientMetricsR\ametrics2\x8a\x02\n" +
	"\x10AAAClientService\x12R\n" +
	"\x13GetConnectionStatus\x12\x1c.pb.ClientHealthCheckRequest\x1a\x1d.pb.ClientHealthCheckResponse\x12S\n" +
	"\x0eRefreshSession\x12\x1f.pb.RefreshClientSessionRequest\x1a .pb.RefreshClientSessionResponse\x12M\n" +
	"\x10GetClientMetrics\x12\x1b.pb.GetClientMetricsRequest\x1a\x1c.pb.GetClientMetricsResponseB2Z0github.com/Kisanlink/aaa-service/v2/pkg/proto;pbb\x06proto3"

var (
	file_aaa_client_proto_rawDescOnce sync.Once
	file_aaa_client_proto_rawDescData []byte
)

func file_aaa_client_proto_rawDescGZIP() []byte {
	file_aaa_client_proto_rawDescOnce.Do(func() {
		file_aaa_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aaa_client_proto_rawDesc), len(file_aaa_client_proto_rawDesc)))
	})
	return file_aaa_client_proto_rawDescData
}

var file_aaa_client_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_aaa_client_proto_goTypes = []any{
	(*AAAClientConfig)(nil),              // 0: pb.AAAClientConfig
	(*ClientConnectionStatus)(nil),       // 1: pb.ClientConnectionStatus
	(*ClientHealthCheckRequest)(nil),     // 2: pb.ClientHealthCheckRequest
	(*ClientHealthCheckResponse)(nil),    // 3: pb.ClientHealthCheckResponse
	(*BatchRequest)(nil),                 // 4: pb.BatchRequest
	(*BatchResponse)(nil),                // 5: pb.BatchResponse
	(*BatchItemResponse)(nil),            // 6: pb.BatchItemResponse
	(*ClientAuthContext)(nil),            // 7: pb.ClientAuthContext
	(*ClientSession)(nil),                // 8: pb.ClientSession
	(*RefreshClientSessionRequest)(nil),  // 9: pb.RefreshClientSessionRequest
	(*RefreshClientSessionResponse)(nil), // 10: pb.RefreshClientSessionResponse
	(*ClientRequestTrace)(nil),           // 11: pb.ClientRequestTrace
	(*ClientMetrics)(nil),                // 12: pb.ClientMetrics
	(*GetClientMetricsRequest)(nil),      // 13: pb.GetClientMetricsRequest
	(*GetClientMetricsResponse)(nil),     // 14: pb.GetClientMetricsResponse
	nil,                                  // 15: pb.AAAClientConfig.MetadataEntry
	nil,                                  // 16: pb.ClientAuthContext.SessionMetadataEntry
	nil,                                  // 17: pb.ClientRequestTrace.TagsEntry
	(*timestamppb.Timestamp)(nil),        // 18: google.protobuf.Timestamp
	(*HealthCheckResponse)(nil),          // 19: pb.HealthCheckResponse
}
var file_aaa_client_proto_depIdxs = []int32{
	15, // 0: pb.AAAClientConfig.metadata:type_name -> pb.AAAClientConfig.MetadataEntry
	18, // 1: pb.ClientConnectionStatus.last_connected:type_name -> google.protobuf.Timestamp
	18, // 2: pb.ClientConnectionStatus.last_heartbeat:type_name -> google.protobuf.Timestamp
	1,  // 3: pb.ClientHealthCheckResponse.connection_status:type_name -> pb.ClientConnectionStatus
	19, // 4: pb.ClientHealthCheckResponse.server_health:type_name -> pb.HealthCheckResponse
	18, // 5: pb.ClientHealthCheckResponse.checked_at:type_name -> google.protobuf.Timestamp
	6,  // 6: pb.BatchResponse.responses:type_name -> pb.BatchItemResponse
	18, // 7: pb.ClientAuthContext.token_expires_at:type_name -> google.protobuf.Timestamp
	16, // 8: pb.ClientAuthContext.session_metadata:type_name -> pb.ClientAuthContext.SessionMetadataEntry
	7,  // 9: pb.ClientSession.auth_context:type_name -> pb.ClientAuthContext
	18, // 10: pb.ClientSession.created_at:type_name -> google.protobuf.Timestamp
	18, // 11: pb.ClientSession.last_activity:type_name -> google.protobuf.Timestamp
	8,  // 12: pb.RefreshClientSessionResponse.session:type_name -> pb.ClientSession
	7,  // 13: pb.RefreshClientSessionResponse.updated_auth:type_name -> pb.ClientAuthContext
	18, // 14: pb.ClientRequestTrace.start_time:type_name -> google.protobuf.Timestamp
	18, // 15: pb.ClientRequestTrace.end_time:type_name -> google.protobuf.Timestamp
	17, // 16: pb.ClientRequestTrace.tags:type_name -> pb.ClientRequestTrace.TagsEntry
	18, // 17: pb.ClientMetrics.metrics_collected_at:type_name -> google.protobuf.Timestamp
	18, // 18: pb.GetClientMetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	18, // 19: pb.GetClientMetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	12, // 20: pb.GetClientMetricsResponse.metrics:type_name -> pb.ClientMetrics
	2,  // 21: pb.AAAClientService.GetConnectionStatus:input_type -> pb.ClientHealthCheckRequest
	9,  // 22: pb.AAAClientService.RefreshSession:input_type -> pb.RefreshClientSessionRequest
	13, // 23: pb.AAAClientService.GetClientMetrics:input_type -> pb.GetClientMetricsRequest
	3,  // 24: pb.AAAClientService.GetConnectionStatus:output_type -> pb.ClientHealthCheckResponse
	10, // 25: pb.AAAClientService.RefreshSession:output_type -> pb.RefreshClientSessionResponse
	14, // 26: pb.AAAClientService.GetClientMetrics:output_type -> pb.GetClientMetricsResponse
	24, // [24:27] is the sub-list for method output_type
	21, // [21:24] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_aaa_client_proto_init() }
func file_aaa_client_proto_init() {
	if File_aaa_client_proto != nil {
		return
	}
	file_aaa_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aaa_client_proto_rawDesc), len(file_aaa_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aaa_client_proto_goTypes,
		DependencyIndexes: file_aaa_client_proto_depIdxs,
		MessageInfos:      file_aaa_client_proto_msgTypes,
	}.Build()
	File_aaa_client_proto = out.File
	file_aaa_client_proto_goTypes = nil
	file_aaa_client_proto_depIdxs = nil
}
