// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: binding.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Binding model
type Binding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectId      string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType    string                 `protobuf:"bytes,3,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`    // "user", "group", "service"
	BindingType    string                 `protobuf:"bytes,4,opt,name=binding_type,json=bindingType,proto3" json:"binding_type,omitempty"`    // "role" or "permission"
	RoleId         string                 `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                   // When binding_type is "role"
	PermissionId   string                 `protobuf:"bytes,6,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"` // When binding_type is "permission"
	ResourceType   string                 `protobuf:"bytes,7,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g., "aaa/table", "aaa/resource"
	ResourceId     string                 `protobuf:"bytes,8,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`       // Specific resource instance
	OrganizationId string                 `protobuf:"bytes,9,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Caveat         *structpb.Struct       `protobuf:"bytes,10,opt,name=caveat,proto3" json:"caveat,omitempty"` // JSON constraints
	Version        int32                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	CreatedById    string                 `protobuf:"bytes,12,opt,name=created_by_id,json=createdById,proto3" json:"created_by_id,omitempty"`
	IsActive       bool                   `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_binding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{0}
}

func (x *Binding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Binding) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Binding) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *Binding) GetBindingType() string {
	if x != nil {
		return x.BindingType
	}
	return ""
}

func (x *Binding) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Binding) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *Binding) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Binding) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Binding) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Binding) GetCaveat() *structpb.Struct {
	if x != nil {
		return x.Caveat
	}
	return nil
}

func (x *Binding) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Binding) GetCreatedById() string {
	if x != nil {
		return x.CreatedById
	}
	return ""
}

func (x *Binding) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Binding) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Binding) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Caveat builder helpers
type TimeCaveat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeCaveat) Reset() {
	*x = TimeCaveat{}
	mi := &file_binding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeCaveat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeCaveat) ProtoMessage() {}

func (x *TimeCaveat) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeCaveat.ProtoReflect.Descriptor instead.
func (*TimeCaveat) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{1}
}

func (x *TimeCaveat) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *TimeCaveat) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

type AttributeCaveat struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequiredAttributes map[string]string      `protobuf:"bytes,1,rep,name=required_attributes,json=requiredAttributes,proto3" json:"required_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttributeCaveat) Reset() {
	*x = AttributeCaveat{}
	mi := &file_binding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeCaveat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeCaveat) ProtoMessage() {}

func (x *AttributeCaveat) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeCaveat.ProtoReflect.Descriptor instead.
func (*AttributeCaveat) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{2}
}

func (x *AttributeCaveat) GetRequiredAttributes() map[string]string {
	if x != nil {
		return x.RequiredAttributes
	}
	return nil
}

type ColumnCaveat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnGroups  []string               `protobuf:"bytes,1,rep,name=column_groups,json=columnGroups,proto3" json:"column_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnCaveat) Reset() {
	*x = ColumnCaveat{}
	mi := &file_binding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnCaveat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnCaveat) ProtoMessage() {}

func (x *ColumnCaveat) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnCaveat.ProtoReflect.Descriptor instead.
func (*ColumnCaveat) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{3}
}

func (x *ColumnCaveat) GetColumnGroups() []string {
	if x != nil {
		return x.ColumnGroups
	}
	return nil
}

// Create Binding Request
type CreateBindingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectId      string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType    string                 `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	BindingType    string                 `protobuf:"bytes,3,opt,name=binding_type,json=bindingType,proto3" json:"binding_type,omitempty"`
	RoleId         string                 `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId   string                 `protobuf:"bytes,5,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	ResourceType   string                 `protobuf:"bytes,6,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId     string                 `protobuf:"bytes,7,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,8,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Caveat options (will be combined into caveat JSON)
	TimeCaveat       *TimeCaveat      `protobuf:"bytes,9,opt,name=time_caveat,json=timeCaveat,proto3" json:"time_caveat,omitempty"`
	AttributeCaveat  *AttributeCaveat `protobuf:"bytes,10,opt,name=attribute_caveat,json=attributeCaveat,proto3" json:"attribute_caveat,omitempty"`
	ColumnCaveat     *ColumnCaveat    `protobuf:"bytes,11,opt,name=column_caveat,json=columnCaveat,proto3" json:"column_caveat,omitempty"`
	CustomCaveat     *structpb.Struct `protobuf:"bytes,12,opt,name=custom_caveat,json=customCaveat,proto3" json:"custom_caveat,omitempty"`                // Additional custom constraints
	WaitUntilApplied bool             `protobuf:"varint,13,opt,name=wait_until_applied,json=waitUntilApplied,proto3" json:"wait_until_applied,omitempty"` // Strict consistency mode
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateBindingRequest) Reset() {
	*x = CreateBindingRequest{}
	mi := &file_binding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindingRequest) ProtoMessage() {}

func (x *CreateBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindingRequest.ProtoReflect.Descriptor instead.
func (*CreateBindingRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBindingRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CreateBindingRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *CreateBindingRequest) GetBindingType() string {
	if x != nil {
		return x.BindingType
	}
	return ""
}

func (x *CreateBindingRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CreateBindingRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *CreateBindingRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CreateBindingRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateBindingRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateBindingRequest) GetTimeCaveat() *TimeCaveat {
	if x != nil {
		return x.TimeCaveat
	}
	return nil
}

func (x *CreateBindingRequest) GetAttributeCaveat() *AttributeCaveat {
	if x != nil {
		return x.AttributeCaveat
	}
	return nil
}

func (x *CreateBindingRequest) GetColumnCaveat() *ColumnCaveat {
	if x != nil {
		return x.ColumnCaveat
	}
	return nil
}

func (x *CreateBindingRequest) GetCustomCaveat() *structpb.Struct {
	if x != nil {
		return x.CustomCaveat
	}
	return nil
}

func (x *CreateBindingRequest) GetWaitUntilApplied() bool {
	if x != nil {
		return x.WaitUntilApplied
	}
	return false
}

// Create Binding Response
type CreateBindingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StatusCode       int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Binding          *Binding               `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	ConsistencyToken string                 `protobuf:"bytes,4,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"` // When wait_until_applied is true
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateBindingResponse) Reset() {
	*x = CreateBindingResponse{}
	mi := &file_binding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindingResponse) ProtoMessage() {}

func (x *CreateBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindingResponse.ProtoReflect.Descriptor instead.
func (*CreateBindingResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBindingResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateBindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBindingResponse) GetBinding() *Binding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *CreateBindingResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// List Bindings Request
type ListBindingsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubjectId        string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType      string                 `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	ResourceType     string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId       string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	IncludeInactive  bool                   `protobuf:"varint,6,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	IncludeInherited bool                   `protobuf:"varint,7,opt,name=include_inherited,json=includeInherited,proto3" json:"include_inherited,omitempty"` // Include bindings from parent groups
	Page             int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListBindingsRequest) Reset() {
	*x = ListBindingsRequest{}
	mi := &file_binding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBindingsRequest) ProtoMessage() {}

func (x *ListBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListBindingsRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{6}
}

func (x *ListBindingsRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ListBindingsRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *ListBindingsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ListBindingsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ListBindingsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListBindingsRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

func (x *ListBindingsRequest) GetIncludeInherited() bool {
	if x != nil {
		return x.IncludeInherited
	}
	return false
}

func (x *ListBindingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBindingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// List Bindings Response
type ListBindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Bindings      []*Binding             `protobuf:"bytes,3,rep,name=bindings,proto3" json:"bindings,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBindingsResponse) Reset() {
	*x = ListBindingsResponse{}
	mi := &file_binding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBindingsResponse) ProtoMessage() {}

func (x *ListBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBindingsResponse.ProtoReflect.Descriptor instead.
func (*ListBindingsResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{7}
}

func (x *ListBindingsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListBindingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListBindingsResponse) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *ListBindingsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListBindingsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBindingsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Get Binding Request
type GetBindingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludeHistory bool                   `protobuf:"varint,2,opt,name=include_history,json=includeHistory,proto3" json:"include_history,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBindingRequest) Reset() {
	*x = GetBindingRequest{}
	mi := &file_binding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBindingRequest) ProtoMessage() {}

func (x *GetBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBindingRequest.ProtoReflect.Descriptor instead.
func (*GetBindingRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{8}
}

func (x *GetBindingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBindingRequest) GetIncludeHistory() bool {
	if x != nil {
		return x.IncludeHistory
	}
	return false
}

// Get Binding Response
type GetBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Binding       *Binding               `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	History       []*BindingHistory      `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBindingResponse) Reset() {
	*x = GetBindingResponse{}
	mi := &file_binding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBindingResponse) ProtoMessage() {}

func (x *GetBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBindingResponse.ProtoReflect.Descriptor instead.
func (*GetBindingResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{9}
}

func (x *GetBindingResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetBindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetBindingResponse) GetBinding() *Binding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *GetBindingResponse) GetHistory() []*BindingHistory {
	if x != nil {
		return x.History
	}
	return nil
}

// Update Binding Request
type UpdateBindingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Caveat updates
	TimeCaveat       *TimeCaveat      `protobuf:"bytes,2,opt,name=time_caveat,json=timeCaveat,proto3" json:"time_caveat,omitempty"`
	AttributeCaveat  *AttributeCaveat `protobuf:"bytes,3,opt,name=attribute_caveat,json=attributeCaveat,proto3" json:"attribute_caveat,omitempty"`
	ColumnCaveat     *ColumnCaveat    `protobuf:"bytes,4,opt,name=column_caveat,json=columnCaveat,proto3" json:"column_caveat,omitempty"`
	CustomCaveat     *structpb.Struct `protobuf:"bytes,5,opt,name=custom_caveat,json=customCaveat,proto3" json:"custom_caveat,omitempty"`
	IsActive         bool             `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	WaitUntilApplied bool             `protobuf:"varint,7,opt,name=wait_until_applied,json=waitUntilApplied,proto3" json:"wait_until_applied,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateBindingRequest) Reset() {
	*x = UpdateBindingRequest{}
	mi := &file_binding_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBindingRequest) ProtoMessage() {}

func (x *UpdateBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBindingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBindingRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateBindingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBindingRequest) GetTimeCaveat() *TimeCaveat {
	if x != nil {
		return x.TimeCaveat
	}
	return nil
}

func (x *UpdateBindingRequest) GetAttributeCaveat() *AttributeCaveat {
	if x != nil {
		return x.AttributeCaveat
	}
	return nil
}

func (x *UpdateBindingRequest) GetColumnCaveat() *ColumnCaveat {
	if x != nil {
		return x.ColumnCaveat
	}
	return nil
}

func (x *UpdateBindingRequest) GetCustomCaveat() *structpb.Struct {
	if x != nil {
		return x.CustomCaveat
	}
	return nil
}

func (x *UpdateBindingRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateBindingRequest) GetWaitUntilApplied() bool {
	if x != nil {
		return x.WaitUntilApplied
	}
	return false
}

// Update Binding Response
type UpdateBindingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StatusCode       int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Binding          *Binding               `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	ConsistencyToken string                 `protobuf:"bytes,4,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateBindingResponse) Reset() {
	*x = UpdateBindingResponse{}
	mi := &file_binding_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBindingResponse) ProtoMessage() {}

func (x *UpdateBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBindingResponse.ProtoReflect.Descriptor instead.
func (*UpdateBindingResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateBindingResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateBindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateBindingResponse) GetBinding() *Binding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *UpdateBindingResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// Delete Binding Request
type DeleteBindingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WaitUntilApplied bool                   `protobuf:"varint,2,opt,name=wait_until_applied,json=waitUntilApplied,proto3" json:"wait_until_applied,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteBindingRequest) Reset() {
	*x = DeleteBindingRequest{}
	mi := &file_binding_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindingRequest) ProtoMessage() {}

func (x *DeleteBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBindingRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBindingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteBindingRequest) GetWaitUntilApplied() bool {
	if x != nil {
		return x.WaitUntilApplied
	}
	return false
}

// Delete Binding Response
type DeleteBindingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StatusCode       int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConsistencyToken string                 `protobuf:"bytes,3,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteBindingResponse) Reset() {
	*x = DeleteBindingResponse{}
	mi := &file_binding_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindingResponse) ProtoMessage() {}

func (x *DeleteBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindingResponse.ProtoReflect.Descriptor instead.
func (*DeleteBindingResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteBindingResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteBindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteBindingResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// Rollback Binding Request
type RollbackBindingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToVersion        int32                  `protobuf:"varint,2,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	WaitUntilApplied bool                   `protobuf:"varint,3,opt,name=wait_until_applied,json=waitUntilApplied,proto3" json:"wait_until_applied,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RollbackBindingRequest) Reset() {
	*x = RollbackBindingRequest{}
	mi := &file_binding_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackBindingRequest) ProtoMessage() {}

func (x *RollbackBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackBindingRequest.ProtoReflect.Descriptor instead.
func (*RollbackBindingRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{14}
}

func (x *RollbackBindingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RollbackBindingRequest) GetToVersion() int32 {
	if x != nil {
		return x.ToVersion
	}
	return 0
}

func (x *RollbackBindingRequest) GetWaitUntilApplied() bool {
	if x != nil {
		return x.WaitUntilApplied
	}
	return false
}

// Rollback Binding Response
type RollbackBindingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StatusCode       int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Binding          *Binding               `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	ConsistencyToken string                 `protobuf:"bytes,4,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RollbackBindingResponse) Reset() {
	*x = RollbackBindingResponse{}
	mi := &file_binding_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackBindingResponse) ProtoMessage() {}

func (x *RollbackBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackBindingResponse.ProtoReflect.Descriptor instead.
func (*RollbackBindingResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{15}
}

func (x *RollbackBindingResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RollbackBindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RollbackBindingResponse) GetBinding() *Binding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *RollbackBindingResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// Binding History model
type BindingHistory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BindingId      string                 `protobuf:"bytes,2,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	SubjectId      string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType    string                 `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	BindingType    string                 `protobuf:"bytes,5,opt,name=binding_type,json=bindingType,proto3" json:"binding_type,omitempty"`
	RoleId         string                 `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId   string                 `protobuf:"bytes,7,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	ResourceType   string                 `protobuf:"bytes,8,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId     string                 `protobuf:"bytes,9,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,10,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Caveat         *structpb.Struct       `protobuf:"bytes,11,opt,name=caveat,proto3" json:"caveat,omitempty"`
	Version        int32                  `protobuf:"varint,12,opt,name=version,proto3" json:"version,omitempty"`
	Action         string                 `protobuf:"bytes,13,opt,name=action,proto3" json:"action,omitempty"` // "CREATE", "UPDATE", "DELETE"
	ChangedById    string                 `protobuf:"bytes,14,opt,name=changed_by_id,json=changedById,proto3" json:"changed_by_id,omitempty"`
	ChangedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BindingHistory) Reset() {
	*x = BindingHistory{}
	mi := &file_binding_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingHistory) ProtoMessage() {}

func (x *BindingHistory) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingHistory.ProtoReflect.Descriptor instead.
func (*BindingHistory) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{16}
}

func (x *BindingHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BindingHistory) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *BindingHistory) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *BindingHistory) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *BindingHistory) GetBindingType() string {
	if x != nil {
		return x.BindingType
	}
	return ""
}

func (x *BindingHistory) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *BindingHistory) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *BindingHistory) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *BindingHistory) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *BindingHistory) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *BindingHistory) GetCaveat() *structpb.Struct {
	if x != nil {
		return x.Caveat
	}
	return nil
}

func (x *BindingHistory) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BindingHistory) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *BindingHistory) GetChangedById() string {
	if x != nil {
		return x.ChangedById
	}
	return ""
}

func (x *BindingHistory) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

// Get Binding History Request
type GetBindingHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BindingId     string                 `protobuf:"bytes,1,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBindingHistoryRequest) Reset() {
	*x = GetBindingHistoryRequest{}
	mi := &file_binding_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBindingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBindingHistoryRequest) ProtoMessage() {}

func (x *GetBindingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBindingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetBindingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{17}
}

func (x *GetBindingHistoryRequest) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *GetBindingHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBindingHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Get Binding History Response
type GetBindingHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	History       []*BindingHistory      `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBindingHistoryResponse) Reset() {
	*x = GetBindingHistoryResponse{}
	mi := &file_binding_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBindingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBindingHistoryResponse) ProtoMessage() {}

func (x *GetBindingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binding_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBindingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetBindingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_binding_proto_rawDescGZIP(), []int{18}
}

func (x *GetBindingHistoryResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetBindingHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetBindingHistoryResponse) GetHistory() []*BindingHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetBindingHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetBindingHistoryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBindingHistoryResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_binding_proto protoreflect.FileDescriptor

const file_binding_proto_rawDesc = "" +
	"\n" +
	"\rbinding.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xad\x04\n" +
	"\aBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x03 \x01(\tR\vsubjectType\x12!\n" +
	"\fbinding_type\x18\x04 \x01(\tR\vbindingType\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\tR\x06roleId\x12#\n" +
	"\rpermission_id\x18\x06 \x01(\tR\fpermissionId\x12#\n" +
	"\rresource_type\x18\a \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\b \x01(\tR\n" +
	"resourceId\x12'\n" +
	"\x0forganization_id\x18\t \x01(\tR\x0eorganizationId\x12/\n" +
	"\x06caveat\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x06caveat\x12\x18\n" +
	"\aversion\x18\v \x01(\x05R\aversion\x12\"\n" +
	"\rcreated_by_id\x18\f \x01(\tR\vcreatedById\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"z\n" +
	"\n" +
	"TimeCaveat\x127\n" +
	"\tstarts_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\"\xb6\x01\n" +
	"\x0fAttributeCaveat\x12\\\n" +
	"\x13required_attributes\x18\x01 \x03(\v2+.pb.AttributeCaveat.RequiredAttributesEntryR\x12requiredAttributes\x1aE\n" +
	"\x17RequiredAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\fColumnCaveat\x12#\n" +
	"\rcolumn_groups\x18\x01 \x03(\tR\fcolumnGroups\"\xbc\x04\n" +
	"\x14CreateBindingRequest\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x02 \x01(\tR\vsubjectType\x12!\n" +
	"\fbinding_type\x18\x03 \x01(\tR\vbindingType\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\tR\x06roleId\x12#\n" +
	"\rpermission_id\x18\x05 \x01(\tR\fpermissionId\x12#\n" +
	"\rresource_type\x18\x06 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\a \x01(\tR\n" +
	"resourceId\x12'\n" +
	"\x0forganization_id\x18\b \x01(\tR\x0eorganizationId\x12/\n" +
	"\vtime_caveat\x18\t \x01(\v2\x0e.pb.TimeCaveatR\n" +
	"timeCaveat\x12>\n" +
	"\x10attribute_caveat\x18\n" +
	" \x01(\v2\x13.pb.AttributeCaveatR\x0fattributeCaveat\x125\n" +
	"\rcolumn_caveat\x18\v \x01(\v2\x10.pb.ColumnCaveatR\fcolumnCaveat\x12<\n" +
	"\rcustom_caveat\x18\f \x01(\v2\x17.google.protobuf.StructR\fcustomCaveat\x12,\n" +
	"\x12wait_until_applied\x18\r \x01(\bR\x10waitUntilApplied\"\xa6\x01\n" +
	"\x15CreateBindingResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\abinding\x18\x03 \x01(\v2\v.pb.BindingR\abinding\x12+\n" +
	"\x11consistency_token\x18\x04 \x01(\tR\x10consistencyToken\"\xcf\x02\n" +
	"\x13ListBindingsRequest\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x02 \x01(\tR\vsubjectType\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\x12)\n" +
	"\x10include_inactive\x18\x06 \x01(\bR\x0fincludeInactive\x12+\n" +
	"\x11include_inherited\x18\a \x01(\bR\x10includeInherited\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\"\xcc\x01\n" +
	"\x14ListBindingsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\bbindings\x18\x03 \x03(\v2\v.pb.BindingR\bbindings\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"L\n" +
	"\x11GetBindingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0finclude_history\x18\x02 \x01(\bR\x0eincludeHistory\"\xa4\x01\n" +
	"\x12GetBindingResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\abinding\x18\x03 \x01(\v2\v.pb.BindingR\abinding\x12,\n" +
	"\ahistory\x18\x04 \x03(\v2\x12.pb.BindingHistoryR\ahistory\"\xd7\x02\n" +
	"\x14UpdateBindingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\vtime_caveat\x18\x02 \x01(\v2\x0e.pb.TimeCaveatR\n" +
	"timeCaveat\x12>\n" +
	"\x10attribute_caveat\x18\x03 \x01(\v2\x13.pb.AttributeCaveatR\x0fattributeCaveat\x125\n" +
	"\rcolumn_caveat\x18\x04 \x01(\v2\x10.pb.ColumnCaveatR\fcolumnCaveat\x12<\n" +
	"\rcustom_caveat\x18\x05 \x01(\v2\x17.google.protobuf.StructR\fcustomCaveat\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12,\n" +
	"\x12wait_until_applied\x18\a \x01(\bR\x10waitUntilApplied\"\xa6\x01\n" +
	"\x15UpdateBindingResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\abinding\x18\x03 \x01(\v2\v.pb.BindingR\abinding\x12+\n" +
	"\x11consistency_token\x18\x04 \x01(\tR\x10consistencyToken\"T\n" +
	"\x14DeleteBindingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12wait_until_applied\x18\x02 \x01(\bR\x10waitUntilApplied\"\x7f\n" +
	"\x15DeleteBindingResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11consistency_token\x18\x03 \x01(\tR\x10consistencyToken\"u\n" +
	"\x16RollbackBindingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"to_version\x18\x02 \x01(\x05R\ttoVersion\x12,\n" +
	"\x12wait_until_applied\x18\x03 \x01(\bR\x10waitUntilApplied\"\xa8\x01\n" +
	"\x17RollbackBindingResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\abinding\x18\x03 \x01(\v2\v.pb.BindingR\abinding\x12+\n" +
	"\x11consistency_token\x18\x04 \x01(\tR\x10consistencyToken\"\x93\x04\n" +
	"\x0eBindingHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x02 \x01(\tR\tbindingId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x04 \x01(\tR\vsubjectType\x12!\n" +
	"\fbinding_type\x18\x05 \x01(\tR\vbindingType\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\tR\x06roleId\x12#\n" +
	"\rpermission_id\x18\a \x01(\tR\fpermissionId\x12#\n" +
	"\rresource_type\x18\b \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\t \x01(\tR\n" +
	"resourceId\x12'\n" +
	"\x0forganization_id\x18\n" +
	" \x01(\tR\x0eorganizationId\x12/\n" +
	"\x06caveat\x18\v \x01(\v2\x17.google.protobuf.StructR\x06caveat\x12\x18\n" +
	"\aversion\x18\f \x01(\x05R\aversion\x12\x16\n" +
	"\x06action\x18\r \x01(\tR\x06action\x12\"\n" +
	"\rchanged_by_id\x18\x0e \x01(\tR\vchangedById\x129\n" +
	"\n" +
	"changed_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\"j\n" +
	"\x18GetBindingHistoryRequest\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x01 \x01(\tR\tbindingId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xd6\x01\n" +
	"\x19GetBindingHistoryResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\ahistory\x18\x03 \x03(\v2\x12.pb.BindingHistoryR\ahistory\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize2\x80\x04\n" +
	"\x0eBindingService\x12D\n" +
	"\rCreateBinding\x12\x18.pb.CreateBindingRequest\x1a\x19.pb.CreateBindingResponse\x12;\n" +
	"\n" +
	"GetBinding\x12\x15.pb.GetBindingRequest\x1a\x16.pb.GetBindingResponse\x12A\n" +
	"\fListBindings\x12\x17.pb.ListBindingsRequest\x1a\x18.pb.ListBindingsResponse\x12D\n" +
	"\rUpdateBinding\x12\x18.pb.UpdateBindingRequest\x1a\x19.pb.UpdateBindingResponse\x12D\n" +
	"\rDeleteBinding\x12\x18.pb.DeleteBindingRequest\x1a\x19.pb.DeleteBindingResponse\x12J\n" +
	"\x0fRollbackBinding\x12\x1a.pb.RollbackBindingRequest\x1a\x1b.pb.RollbackBindingResponse\x12P\n" +
	"\x11GetBindingHistory\x12\x1c.pb.GetBindingHistoryRequest\x1a\x1d.pb.GetBindingHistoryResponseB/Z-github.com/Kisanlink/aaa-service/pkg/proto;pbb\x06proto3"

var (
	file_binding_proto_rawDescOnce sync.Once
	file_binding_proto_rawDescData []byte
)

func file_binding_proto_rawDescGZIP() []byte {
	file_binding_proto_rawDescOnce.Do(func() {
		file_binding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_binding_proto_rawDesc), len(file_binding_proto_rawDesc)))
	})
	return file_binding_proto_rawDescData
}

var file_binding_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_binding_proto_goTypes = []any{
	(*Binding)(nil),                   // 0: pb.Binding
	(*TimeCaveat)(nil),                // 1: pb.TimeCaveat
	(*AttributeCaveat)(nil),           // 2: pb.AttributeCaveat
	(*ColumnCaveat)(nil),              // 3: pb.ColumnCaveat
	(*CreateBindingRequest)(nil),      // 4: pb.CreateBindingRequest
	(*CreateBindingResponse)(nil),     // 5: pb.CreateBindingResponse
	(*ListBindingsRequest)(nil),       // 6: pb.ListBindingsRequest
	(*ListBindingsResponse)(nil),      // 7: pb.ListBindingsResponse
	(*GetBindingRequest)(nil),         // 8: pb.GetBindingRequest
	(*GetBindingResponse)(nil),        // 9: pb.GetBindingResponse
	(*UpdateBindingRequest)(nil),      // 10: pb.UpdateBindingRequest
	(*UpdateBindingResponse)(nil),     // 11: pb.UpdateBindingResponse
	(*DeleteBindingRequest)(nil),      // 12: pb.DeleteBindingRequest
	(*DeleteBindingResponse)(nil),     // 13: pb.DeleteBindingResponse
	(*RollbackBindingRequest)(nil),    // 14: pb.RollbackBindingRequest
	(*RollbackBindingResponse)(nil),   // 15: pb.RollbackBindingResponse
	(*BindingHistory)(nil),            // 16: pb.BindingHistory
	(*GetBindingHistoryRequest)(nil),  // 17: pb.GetBindingHistoryRequest
	(*GetBindingHistoryResponse)(nil), // 18: pb.GetBindingHistoryResponse
	nil,                               // 19: pb.AttributeCaveat.RequiredAttributesEntry
	(*structpb.Struct)(nil),           // 20: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
}
var file_binding_proto_depIdxs = []int32{
	20, // 0: pb.Binding.caveat:type_name -> google.protobuf.Struct
	21, // 1: pb.Binding.created_at:type_name -> google.protobuf.Timestamp
	21, // 2: pb.Binding.updated_at:type_name -> google.protobuf.Timestamp
	21, // 3: pb.TimeCaveat.starts_at:type_name -> google.protobuf.Timestamp
	21, // 4: pb.TimeCaveat.ends_at:type_name -> google.protobuf.Timestamp
	19, // 5: pb.AttributeCaveat.required_attributes:type_name -> pb.AttributeCaveat.RequiredAttributesEntry
	1,  // 6: pb.CreateBindingRequest.time_caveat:type_name -> pb.TimeCaveat
	2,  // 7: pb.CreateBindingRequest.attribute_caveat:type_name -> pb.AttributeCaveat
	3,  // 8: pb.CreateBindingRequest.column_caveat:type_name -> pb.ColumnCaveat
	20, // 9: pb.CreateBindingRequest.custom_caveat:type_name -> google.protobuf.Struct
	0,  // 10: pb.CreateBindingResponse.binding:type_name -> pb.Binding
	0,  // 11: pb.ListBindingsResponse.bindings:type_name -> pb.Binding
	0,  // 12: pb.GetBindingResponse.binding:type_name -> pb.Binding
	16, // 13: pb.GetBindingResponse.history:type_name -> pb.BindingHistory
	1,  // 14: pb.UpdateBindingRequest.time_caveat:type_name -> pb.TimeCaveat
	2,  // 15: pb.UpdateBindingRequest.attribute_caveat:type_name -> pb.AttributeCaveat
	3,  // 16: pb.UpdateBindingRequest.column_caveat:type_name -> pb.ColumnCaveat
	20, // 17: pb.UpdateBindingRequest.custom_caveat:type_name -> google.protobuf.Struct
	0,  // 18: pb.UpdateBindingResponse.binding:type_name -> pb.Binding
	0,  // 19: pb.RollbackBindingResponse.binding:type_name -> pb.Binding
	20, // 20: pb.BindingHistory.caveat:type_name -> google.protobuf.Struct
	21, // 21: pb.BindingHistory.changed_at:type_name -> google.protobuf.Timestamp
	16, // 22: pb.GetBindingHistoryResponse.history:type_name -> pb.BindingHistory
	4,  // 23: pb.BindingService.CreateBinding:input_type -> pb.CreateBindingRequest
	8,  // 24: pb.BindingService.GetBinding:input_type -> pb.GetBindingRequest
	6,  // 25: pb.BindingService.ListBindings:input_type -> pb.ListBindingsRequest
	10, // 26: pb.BindingService.UpdateBinding:input_type -> pb.UpdateBindingRequest
	12, // 27: pb.BindingService.DeleteBinding:input_type -> pb.DeleteBindingRequest
	14, // 28: pb.BindingService.RollbackBinding:input_type -> pb.RollbackBindingRequest
	17, // 29: pb.BindingService.GetBindingHistory:input_type -> pb.GetBindingHistoryRequest
	5,  // 30: pb.BindingService.CreateBinding:output_type -> pb.CreateBindingResponse
	9,  // 31: pb.BindingService.GetBinding:output_type -> pb.GetBindingResponse
	7,  // 32: pb.BindingService.ListBindings:output_type -> pb.ListBindingsResponse
	11, // 33: pb.BindingService.UpdateBinding:output_type -> pb.UpdateBindingResponse
	13, // 34: pb.BindingService.DeleteBinding:output_type -> pb.DeleteBindingResponse
	15, // 35: pb.BindingService.RollbackBinding:output_type -> pb.RollbackBindingResponse
	18, // 36: pb.BindingService.GetBindingHistory:output_type -> pb.GetBindingHistoryResponse
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_binding_proto_init() }
func file_binding_proto_init() {
	if File_binding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_binding_proto_rawDesc), len(file_binding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_binding_proto_goTypes,
		DependencyIndexes: file_binding_proto_depIdxs,
		MessageInfos:      file_binding_proto_msgTypes,
	}.Build()
	File_binding_proto = out.File
	file_binding_proto_goTypes = nil
	file_binding_proto_depIdxs = nil
}
