// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: contract.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contract model - defines service surface
type Contract struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceId      string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Manifest       *ContractManifest      `protobuf:"bytes,6,opt,name=manifest,proto3" json:"manifest,omitempty"`
	OrganizationId string                 `protobuf:"bytes,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ApprovedById   string                 `protobuf:"bytes,8,opt,name=approved_by_id,json=approvedById,proto3" json:"approved_by_id,omitempty"`
	ApprovedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	IsActive       bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

func (x *Contract) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contract) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Contract) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contract) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Contract) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Contract) GetManifest() *ContractManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *Contract) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Contract) GetApprovedById() string {
	if x != nil {
		return x.ApprovedById
	}
	return ""
}

func (x *Contract) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *Contract) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Contract) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Contract) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Contract manifest defining resources, actions, and default bindings
type ContractManifest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceName     string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion  string                 `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	Resources       []*ResourceDefinition  `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	Actions         []*ActionDefinition    `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	Roles           []*RoleTemplate        `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	DefaultBindings []*DefaultBinding      `protobuf:"bytes,6,rep,name=default_bindings,json=defaultBindings,proto3" json:"default_bindings,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContractManifest) Reset() {
	*x = ContractManifest{}
	mi := &file_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractManifest) ProtoMessage() {}

func (x *ContractManifest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractManifest.ProtoReflect.Descriptor instead.
func (*ContractManifest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

func (x *ContractManifest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ContractManifest) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *ContractManifest) GetResources() []*ResourceDefinition {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ContractManifest) GetActions() []*ActionDefinition {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ContractManifest) GetRoles() []*RoleTemplate {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ContractManifest) GetDefaultBindings() []*DefaultBinding {
	if x != nil {
		return x.DefaultBindings
	}
	return nil
}

func (x *ContractManifest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Resource definition in contract
type ResourceDefinition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ParentType      string                 `protobuf:"bytes,4,opt,name=parent_type,json=parentType,proto3" json:"parent_type,omitempty"` // Optional parent resource type
	RequiredActions []string               `protobuf:"bytes,5,rep,name=required_actions,json=requiredActions,proto3" json:"required_actions,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceDefinition) Reset() {
	*x = ResourceDefinition{}
	mi := &file_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDefinition) ProtoMessage() {}

func (x *ResourceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDefinition.ProtoReflect.Descriptor instead.
func (*ResourceDefinition) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResourceDefinition) GetParentType() string {
	if x != nil {
		return x.ParentType
	}
	return ""
}

func (x *ResourceDefinition) GetRequiredActions() []string {
	if x != nil {
		return x.RequiredActions
	}
	return nil
}

func (x *ResourceDefinition) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Action definition in contract
type ActionDefinition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ApplicableResources []string               `protobuf:"bytes,3,rep,name=applicable_resources,json=applicableResources,proto3" json:"applicable_resources,omitempty"` // Resource types this action applies to
	RequiresWrite       bool                   `protobuf:"varint,4,opt,name=requires_write,json=requiresWrite,proto3" json:"requires_write,omitempty"`
	RequiresAdmin       bool                   `protobuf:"varint,5,opt,name=requires_admin,json=requiresAdmin,proto3" json:"requires_admin,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActionDefinition) Reset() {
	*x = ActionDefinition{}
	mi := &file_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDefinition) ProtoMessage() {}

func (x *ActionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDefinition.ProtoReflect.Descriptor instead.
func (*ActionDefinition) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ActionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionDefinition) GetApplicableResources() []string {
	if x != nil {
		return x.ApplicableResources
	}
	return nil
}

func (x *ActionDefinition) GetRequiresWrite() bool {
	if x != nil {
		return x.RequiresWrite
	}
	return false
}

func (x *ActionDefinition) GetRequiresAdmin() bool {
	if x != nil {
		return x.RequiresAdmin
	}
	return false
}

// Role template in contract
type RoleTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"` // "GLOBAL" or "ORG"
	Permissions   []*PermissionGrant     `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleTemplate) Reset() {
	*x = RoleTemplate{}
	mi := &file_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleTemplate) ProtoMessage() {}

func (x *RoleTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleTemplate.ProtoReflect.Descriptor instead.
func (*RoleTemplate) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{4}
}

func (x *RoleTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleTemplate) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RoleTemplate) GetPermissions() []*PermissionGrant {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Permission grant in role template
type PermissionGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Actions       []string               `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionGrant) Reset() {
	*x = PermissionGrant{}
	mi := &file_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionGrant) ProtoMessage() {}

func (x *PermissionGrant) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionGrant.ProtoReflect.Descriptor instead.
func (*PermissionGrant) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{5}
}

func (x *PermissionGrant) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *PermissionGrant) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

// Default binding to create
type DefaultBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	SubjectType   string                 `protobuf:"bytes,3,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"` // "owner", "admin_group", etc.
	Caveat        *structpb.Struct       `protobuf:"bytes,4,opt,name=caveat,proto3" json:"caveat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultBinding) Reset() {
	*x = DefaultBinding{}
	mi := &file_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultBinding) ProtoMessage() {}

func (x *DefaultBinding) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultBinding.ProtoReflect.Descriptor instead.
func (*DefaultBinding) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{6}
}

func (x *DefaultBinding) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *DefaultBinding) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *DefaultBinding) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *DefaultBinding) GetCaveat() *structpb.Struct {
	if x != nil {
		return x.Caveat
	}
	return nil
}

// Apply Contract Request
type ApplyContractRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Manifest       *ContractManifest      `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	DryRun         bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"` // Validate without applying
	Force          bool                   `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`                 // Force apply even with conflicts
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyContractRequest) Reset() {
	*x = ApplyContractRequest{}
	mi := &file_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyContractRequest) ProtoMessage() {}

func (x *ApplyContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyContractRequest.ProtoReflect.Descriptor instead.
func (*ApplyContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyContractRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ApplyContractRequest) GetManifest() *ContractManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *ApplyContractRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ApplyContractRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ApplyContractRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Apply Contract Response
type ApplyContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Contract      *Contract              `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Diff          *ContractDiff          `protobuf:"bytes,4,opt,name=diff,proto3" json:"diff,omitempty"`
	Warnings      []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyContractResponse) Reset() {
	*x = ApplyContractResponse{}
	mi := &file_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyContractResponse) ProtoMessage() {}

func (x *ApplyContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyContractResponse.ProtoReflect.Descriptor instead.
func (*ApplyContractResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyContractResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ApplyContractResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApplyContractResponse) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *ApplyContractResponse) GetDiff() *ContractDiff {
	if x != nil {
		return x.Diff
	}
	return nil
}

func (x *ApplyContractResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Contract diff showing what will change
type ContractDiff struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	ResourceChanges []*ContractDiff_ResourceChange `protobuf:"bytes,1,rep,name=resource_changes,json=resourceChanges,proto3" json:"resource_changes,omitempty"`
	ActionChanges   []*ContractDiff_ActionChange   `protobuf:"bytes,2,rep,name=action_changes,json=actionChanges,proto3" json:"action_changes,omitempty"`
	RoleChanges     []*ContractDiff_RoleChange     `protobuf:"bytes,3,rep,name=role_changes,json=roleChanges,proto3" json:"role_changes,omitempty"`
	BindingChanges  []*ContractDiff_BindingChange  `protobuf:"bytes,4,rep,name=binding_changes,json=bindingChanges,proto3" json:"binding_changes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContractDiff) Reset() {
	*x = ContractDiff{}
	mi := &file_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDiff) ProtoMessage() {}

func (x *ContractDiff) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDiff.ProtoReflect.Descriptor instead.
func (*ContractDiff) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{9}
}

func (x *ContractDiff) GetResourceChanges() []*ContractDiff_ResourceChange {
	if x != nil {
		return x.ResourceChanges
	}
	return nil
}

func (x *ContractDiff) GetActionChanges() []*ContractDiff_ActionChange {
	if x != nil {
		return x.ActionChanges
	}
	return nil
}

func (x *ContractDiff) GetRoleChanges() []*ContractDiff_RoleChange {
	if x != nil {
		return x.RoleChanges
	}
	return nil
}

func (x *ContractDiff) GetBindingChanges() []*ContractDiff_BindingChange {
	if x != nil {
		return x.BindingChanges
	}
	return nil
}

// Get Contract Request
type GetContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludeDiff   bool                   `protobuf:"varint,2,opt,name=include_diff,json=includeDiff,proto3" json:"include_diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractRequest) Reset() {
	*x = GetContractRequest{}
	mi := &file_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractRequest) ProtoMessage() {}

func (x *GetContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractRequest.ProtoReflect.Descriptor instead.
func (*GetContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{10}
}

func (x *GetContractRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetContractRequest) GetIncludeDiff() bool {
	if x != nil {
		return x.IncludeDiff
	}
	return false
}

// Get Contract Response
type GetContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Contract      *Contract              `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Diff          *ContractDiff          `protobuf:"bytes,4,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractResponse) Reset() {
	*x = GetContractResponse{}
	mi := &file_contract_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractResponse) ProtoMessage() {}

func (x *GetContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractResponse.ProtoReflect.Descriptor instead.
func (*GetContractResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{11}
}

func (x *GetContractResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetContractResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetContractResponse) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *GetContractResponse) GetDiff() *ContractDiff {
	if x != nil {
		return x.Diff
	}
	return nil
}

// List Contracts Request
type ListContractsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	OrganizationId  string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	IncludeInactive bool                   `protobuf:"varint,3,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	Page            int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize        int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListContractsRequest) Reset() {
	*x = ListContractsRequest{}
	mi := &file_contract_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractsRequest) ProtoMessage() {}

func (x *ListContractsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractsRequest.ProtoReflect.Descriptor instead.
func (*ListContractsRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{12}
}

func (x *ListContractsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ListContractsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListContractsRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

func (x *ListContractsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListContractsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// List Contracts Response
type ListContractsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Contracts     []*Contract            `protobuf:"bytes,3,rep,name=contracts,proto3" json:"contracts,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractsResponse) Reset() {
	*x = ListContractsResponse{}
	mi := &file_contract_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractsResponse) ProtoMessage() {}

func (x *ListContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractsResponse.ProtoReflect.Descriptor instead.
func (*ListContractsResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{13}
}

func (x *ListContractsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListContractsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListContractsResponse) GetContracts() []*Contract {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *ListContractsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListContractsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListContractsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Validate Contract Request
type ValidateContractRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Manifest       *ContractManifest      `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateContractRequest) Reset() {
	*x = ValidateContractRequest{}
	mi := &file_contract_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateContractRequest) ProtoMessage() {}

func (x *ValidateContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateContractRequest.ProtoReflect.Descriptor instead.
func (*ValidateContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateContractRequest) GetManifest() *ContractManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *ValidateContractRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

// Validate Contract Response
type ValidateContractResponse struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	StatusCode    int32                                       `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsValid       bool                                        `protobuf:"varint,3,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Errors        []*ValidateContractResponse_ValidationError `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string                                    `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateContractResponse) Reset() {
	*x = ValidateContractResponse{}
	mi := &file_contract_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateContractResponse) ProtoMessage() {}

func (x *ValidateContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateContractResponse.ProtoReflect.Descriptor instead.
func (*ValidateContractResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateContractResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ValidateContractResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateContractResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateContractResponse) GetErrors() []*ValidateContractResponse_ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateContractResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Revert Contract Request
type RevertContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertContractRequest) Reset() {
	*x = RevertContractRequest{}
	mi := &file_contract_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertContractRequest) ProtoMessage() {}

func (x *RevertContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertContractRequest.ProtoReflect.Descriptor instead.
func (*RevertContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{16}
}

func (x *RevertContractRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RevertContractRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Revert Contract Response
type RevertContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RevertDiff    *ContractDiff          `protobuf:"bytes,3,opt,name=revert_diff,json=revertDiff,proto3" json:"revert_diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertContractResponse) Reset() {
	*x = RevertContractResponse{}
	mi := &file_contract_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertContractResponse) ProtoMessage() {}

func (x *RevertContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertContractResponse.ProtoReflect.Descriptor instead.
func (*RevertContractResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{17}
}

func (x *RevertContractResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RevertContractResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RevertContractResponse) GetRevertDiff() *ContractDiff {
	if x != nil {
		return x.RevertDiff
	}
	return nil
}

// Get Contract Template Request
type GetContractTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateType  string                 `protobuf:"bytes,1,opt,name=template_type,json=templateType,proto3" json:"template_type,omitempty"` // e.g., "microservice", "database", "api"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractTemplateRequest) Reset() {
	*x = GetContractTemplateRequest{}
	mi := &file_contract_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractTemplateRequest) ProtoMessage() {}

func (x *GetContractTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetContractTemplateRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{18}
}

func (x *GetContractTemplateRequest) GetTemplateType() string {
	if x != nil {
		return x.TemplateType
	}
	return ""
}

// Get Contract Template Response
type GetContractTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Template      *ContractManifest      `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractTemplateResponse) Reset() {
	*x = GetContractTemplateResponse{}
	mi := &file_contract_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractTemplateResponse) ProtoMessage() {}

func (x *GetContractTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetContractTemplateResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{19}
}

func (x *GetContractTemplateResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetContractTemplateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetContractTemplateResponse) GetTemplate() *ContractManifest {
	if x != nil {
		return x.Template
	}
	return nil
}

type ContractDiff_ResourceChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    string                 `protobuf:"bytes,1,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"` // "CREATE", "UPDATE", "DELETE"
	Resource      *ResourceDefinition    `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractDiff_ResourceChange) Reset() {
	*x = ContractDiff_ResourceChange{}
	mi := &file_contract_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractDiff_ResourceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDiff_ResourceChange) ProtoMessage() {}

func (x *ContractDiff_ResourceChange) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDiff_ResourceChange.ProtoReflect.Descriptor instead.
func (*ContractDiff_ResourceChange) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ContractDiff_ResourceChange) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ContractDiff_ResourceChange) GetResource() *ResourceDefinition {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ContractDiff_ActionChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    string                 `protobuf:"bytes,1,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	Action        *ActionDefinition      `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractDiff_ActionChange) Reset() {
	*x = ContractDiff_ActionChange{}
	mi := &file_contract_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractDiff_ActionChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDiff_ActionChange) ProtoMessage() {}

func (x *ContractDiff_ActionChange) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDiff_ActionChange.ProtoReflect.Descriptor instead.
func (*ContractDiff_ActionChange) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{9, 1}
}

func (x *ContractDiff_ActionChange) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ContractDiff_ActionChange) GetAction() *ActionDefinition {
	if x != nil {
		return x.Action
	}
	return nil
}

type ContractDiff_RoleChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    string                 `protobuf:"bytes,1,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	Role          *RoleTemplate          `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractDiff_RoleChange) Reset() {
	*x = ContractDiff_RoleChange{}
	mi := &file_contract_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractDiff_RoleChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDiff_RoleChange) ProtoMessage() {}

func (x *ContractDiff_RoleChange) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDiff_RoleChange.ProtoReflect.Descriptor instead.
func (*ContractDiff_RoleChange) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{9, 2}
}

func (x *ContractDiff_RoleChange) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ContractDiff_RoleChange) GetRole() *RoleTemplate {
	if x != nil {
		return x.Role
	}
	return nil
}

type ContractDiff_BindingChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    string                 `protobuf:"bytes,1,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	Binding       *DefaultBinding        `protobuf:"bytes,2,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractDiff_BindingChange) Reset() {
	*x = ContractDiff_BindingChange{}
	mi := &file_contract_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractDiff_BindingChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDiff_BindingChange) ProtoMessage() {}

func (x *ContractDiff_BindingChange) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDiff_BindingChange.ProtoReflect.Descriptor instead.
func (*ContractDiff_BindingChange) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{9, 3}
}

func (x *ContractDiff_BindingChange) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ContractDiff_BindingChange) GetBinding() *DefaultBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

type ValidateContractResponse_ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateContractResponse_ValidationError) Reset() {
	*x = ValidateContractResponse_ValidationError{}
	mi := &file_contract_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateContractResponse_ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateContractResponse_ValidationError) ProtoMessage() {}

func (x *ValidateContractResponse_ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateContractResponse_ValidationError.ProtoReflect.Descriptor instead.
func (*ValidateContractResponse_ValidationError) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{15, 0}
}

func (x *ValidateContractResponse_ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidateContractResponse_ValidationError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_contract_proto protoreflect.FileDescriptor

const file_contract_proto_rawDesc = "" +
	"\n" +
	"\x0econtract.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xda\x03\n" +
	"\bContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x120\n" +
	"\bmanifest\x18\x06 \x01(\v2\x14.pb.ContractManifestR\bmanifest\x12'\n" +
	"\x0forganization_id\x18\a \x01(\tR\x0eorganizationId\x12$\n" +
	"\x0eapproved_by_id\x18\b \x01(\tR\fapprovedById\x12;\n" +
	"\vapproved_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe0\x02\n" +
	"\x10ContractManifest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x02 \x01(\tR\x0eserviceVersion\x124\n" +
	"\tresources\x18\x03 \x03(\v2\x16.pb.ResourceDefinitionR\tresources\x12.\n" +
	"\aactions\x18\x04 \x03(\v2\x14.pb.ActionDefinitionR\aactions\x12&\n" +
	"\x05roles\x18\x05 \x03(\v2\x10.pb.RoleTemplateR\x05roles\x12=\n" +
	"\x10default_bindings\x18\x06 \x03(\v2\x12.pb.DefaultBindingR\x0fdefaultBindings\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xa9\x02\n" +
	"\x12ResourceDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vparent_type\x18\x04 \x01(\tR\n" +
	"parentType\x12)\n" +
	"\x10required_actions\x18\x05 \x03(\tR\x0frequiredActions\x12@\n" +
	"\bmetadata\x18\x06 \x03(\v2$.pb.ResourceDefinition.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x10ActionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x121\n" +
	"\x14applicable_resources\x18\x03 \x03(\tR\x13applicableResources\x12%\n" +
	"\x0erequires_write\x18\x04 \x01(\bR\rrequiresWrite\x12%\n" +
	"\x0erequires_admin\x18\x05 \x01(\bR\rrequiresAdmin\"\x91\x01\n" +
	"\fRoleTemplate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x125\n" +
	"\vpermissions\x18\x04 \x03(\v2\x13.pb.PermissionGrantR\vpermissions\"P\n" +
	"\x0fPermissionGrant\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions\"\xa6\x01\n" +
	"\x0eDefaultBinding\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12!\n" +
	"\fsubject_type\x18\x03 \x01(\tR\vsubjectType\x12/\n" +
	"\x06caveat\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06caveat\"\xbf\x01\n" +
	"\x14ApplyContractRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x120\n" +
	"\bmanifest\x18\x02 \x01(\v2\x14.pb.ContractManifestR\bmanifest\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\x12\x14\n" +
	"\x05force\x18\x05 \x01(\bR\x05force\"\xbe\x01\n" +
	"\x15ApplyContractResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\bcontract\x18\x03 \x01(\v2\f.pb.ContractR\bcontract\x12$\n" +
	"\x04diff\x18\x04 \x01(\v2\x10.pb.ContractDiffR\x04diff\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\"\xa4\x05\n" +
	"\fContractDiff\x12J\n" +
	"\x10resource_changes\x18\x01 \x03(\v2\x1f.pb.ContractDiff.ResourceChangeR\x0fresourceChanges\x12D\n" +
	"\x0eaction_changes\x18\x02 \x03(\v2\x1d.pb.ContractDiff.ActionChangeR\ractionChanges\x12>\n" +
	"\frole_changes\x18\x03 \x03(\v2\x1b.pb.ContractDiff.RoleChangeR\vroleChanges\x12G\n" +
	"\x0fbinding_changes\x18\x04 \x03(\v2\x1e.pb.ContractDiff.BindingChangeR\x0ebindingChanges\x1ae\n" +
	"\x0eResourceChange\x12\x1f\n" +
	"\vchange_type\x18\x01 \x01(\tR\n" +
	"changeType\x122\n" +
	"\bresource\x18\x02 \x01(\v2\x16.pb.ResourceDefinitionR\bresource\x1a]\n" +
	"\fActionChange\x12\x1f\n" +
	"\vchange_type\x18\x01 \x01(\tR\n" +
	"changeType\x12,\n" +
	"\x06action\x18\x02 \x01(\v2\x14.pb.ActionDefinitionR\x06action\x1aS\n" +
	"\n" +
	"RoleChange\x12\x1f\n" +
	"\vchange_type\x18\x01 \x01(\tR\n" +
	"changeType\x12$\n" +
	"\x04role\x18\x02 \x01(\v2\x10.pb.RoleTemplateR\x04role\x1a^\n" +
	"\rBindingChange\x12\x1f\n" +
	"\vchange_type\x18\x01 \x01(\tR\n" +
	"changeType\x12,\n" +
	"\abinding\x18\x02 \x01(\v2\x12.pb.DefaultBindingR\abinding\"G\n" +
	"\x12GetContractRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\finclude_diff\x18\x02 \x01(\bR\vincludeDiff\"\xa0\x01\n" +
	"\x13GetContractResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\bcontract\x18\x03 \x01(\v2\f.pb.ContractR\bcontract\x12$\n" +
	"\x04diff\x18\x04 \x01(\v2\x10.pb.ContractDiffR\x04diff\"\xba\x01\n" +
	"\x14ListContractsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12)\n" +
	"\x10include_inactive\x18\x03 \x01(\bR\x0fincludeInactive\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xd0\x01\n" +
	"\x15ListContractsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\tcontracts\x18\x03 \x03(\v2\f.pb.ContractR\tcontracts\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"t\n" +
	"\x17ValidateContractRequest\x120\n" +
	"\bmanifest\x18\x01 \x01(\v2\x14.pb.ContractManifestR\bmanifest\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\x91\x02\n" +
	"\x18ValidateContractResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bis_valid\x18\x03 \x01(\bR\aisValid\x12D\n" +
	"\x06errors\x18\x04 \x03(\v2,.pb.ValidateContractResponse.ValidationErrorR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\x1a=\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"=\n" +
	"\x15RevertContractRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x86\x01\n" +
	"\x16RevertContractResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\vrevert_diff\x18\x03 \x01(\v2\x10.pb.ContractDiffR\n" +
	"revertDiff\"A\n" +
	"\x1aGetContractTemplateRequest\x12#\n" +
	"\rtemplate_type\x18\x01 \x01(\tR\ftemplateType\"\x8a\x01\n" +
	"\x1bGetContractTemplateResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\btemplate\x18\x03 \x01(\v2\x14.pb.ContractManifestR\btemplate2\xcd\x03\n" +
	"\x0fContractService\x12D\n" +
	"\rApplyContract\x12\x18.pb.ApplyContractRequest\x1a\x19.pb.ApplyContractResponse\x12>\n" +
	"\vGetContract\x12\x16.pb.GetContractRequest\x1a\x17.pb.GetContractResponse\x12D\n" +
	"\rListContracts\x12\x18.pb.ListContractsRequest\x1a\x19.pb.ListContractsResponse\x12M\n" +
	"\x10ValidateContract\x12\x1b.pb.ValidateContractRequest\x1a\x1c.pb.ValidateContractResponse\x12G\n" +
	"\x0eRevertContract\x12\x19.pb.RevertContractRequest\x1a\x1a.pb.RevertContractResponse\x12V\n" +
	"\x13GetContractTemplate\x12\x1e.pb.GetContractTemplateRequest\x1a\x1f.pb.GetContractTemplateResponseB/Z-github.com/Kisanlink/aaa-service/pkg/proto;pbb\x06proto3"

var (
	file_contract_proto_rawDescOnce sync.Once
	file_contract_proto_rawDescData []byte
)

func file_contract_proto_rawDescGZIP() []byte {
	file_contract_proto_rawDescOnce.Do(func() {
		file_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)))
	})
	return file_contract_proto_rawDescData
}

var file_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_contract_proto_goTypes = []any{
	(*Contract)(nil),                                 // 0: pb.Contract
	(*ContractManifest)(nil),                         // 1: pb.ContractManifest
	(*ResourceDefinition)(nil),                       // 2: pb.ResourceDefinition
	(*ActionDefinition)(nil),                         // 3: pb.ActionDefinition
	(*RoleTemplate)(nil),                             // 4: pb.RoleTemplate
	(*PermissionGrant)(nil),                          // 5: pb.PermissionGrant
	(*DefaultBinding)(nil),                           // 6: pb.DefaultBinding
	(*ApplyContractRequest)(nil),                     // 7: pb.ApplyContractRequest
	(*ApplyContractResponse)(nil),                    // 8: pb.ApplyContractResponse
	(*ContractDiff)(nil),                             // 9: pb.ContractDiff
	(*GetContractRequest)(nil),                       // 10: pb.GetContractRequest
	(*GetContractResponse)(nil),                      // 11: pb.GetContractResponse
	(*ListContractsRequest)(nil),                     // 12: pb.ListContractsRequest
	(*ListContractsResponse)(nil),                    // 13: pb.ListContractsResponse
	(*ValidateContractRequest)(nil),                  // 14: pb.ValidateContractRequest
	(*ValidateContractResponse)(nil),                 // 15: pb.ValidateContractResponse
	(*RevertContractRequest)(nil),                    // 16: pb.RevertContractRequest
	(*RevertContractResponse)(nil),                   // 17: pb.RevertContractResponse
	(*GetContractTemplateRequest)(nil),               // 18: pb.GetContractTemplateRequest
	(*GetContractTemplateResponse)(nil),              // 19: pb.GetContractTemplateResponse
	nil,                                              // 20: pb.ResourceDefinition.MetadataEntry
	(*ContractDiff_ResourceChange)(nil),              // 21: pb.ContractDiff.ResourceChange
	(*ContractDiff_ActionChange)(nil),                // 22: pb.ContractDiff.ActionChange
	(*ContractDiff_RoleChange)(nil),                  // 23: pb.ContractDiff.RoleChange
	(*ContractDiff_BindingChange)(nil),               // 24: pb.ContractDiff.BindingChange
	(*ValidateContractResponse_ValidationError)(nil), // 25: pb.ValidateContractResponse.ValidationError
	(*timestamppb.Timestamp)(nil),                    // 26: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                          // 27: google.protobuf.Struct
}
var file_contract_proto_depIdxs = []int32{
	1,  // 0: pb.Contract.manifest:type_name -> pb.ContractManifest
	26, // 1: pb.Contract.approved_at:type_name -> google.protobuf.Timestamp
	26, // 2: pb.Contract.created_at:type_name -> google.protobuf.Timestamp
	26, // 3: pb.Contract.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: pb.ContractManifest.resources:type_name -> pb.ResourceDefinition
	3,  // 5: pb.ContractManifest.actions:type_name -> pb.ActionDefinition
	4,  // 6: pb.ContractManifest.roles:type_name -> pb.RoleTemplate
	6,  // 7: pb.ContractManifest.default_bindings:type_name -> pb.DefaultBinding
	27, // 8: pb.ContractManifest.metadata:type_name -> google.protobuf.Struct
	20, // 9: pb.ResourceDefinition.metadata:type_name -> pb.ResourceDefinition.MetadataEntry
	5,  // 10: pb.RoleTemplate.permissions:type_name -> pb.PermissionGrant
	27, // 11: pb.DefaultBinding.caveat:type_name -> google.protobuf.Struct
	1,  // 12: pb.ApplyContractRequest.manifest:type_name -> pb.ContractManifest
	0,  // 13: pb.ApplyContractResponse.contract:type_name -> pb.Contract
	9,  // 14: pb.ApplyContractResponse.diff:type_name -> pb.ContractDiff
	21, // 15: pb.ContractDiff.resource_changes:type_name -> pb.ContractDiff.ResourceChange
	22, // 16: pb.ContractDiff.action_changes:type_name -> pb.ContractDiff.ActionChange
	23, // 17: pb.ContractDiff.role_changes:type_name -> pb.ContractDiff.RoleChange
	24, // 18: pb.ContractDiff.binding_changes:type_name -> pb.ContractDiff.BindingChange
	0,  // 19: pb.GetContractResponse.contract:type_name -> pb.Contract
	9,  // 20: pb.GetContractResponse.diff:type_name -> pb.ContractDiff
	0,  // 21: pb.ListContractsResponse.contracts:type_name -> pb.Contract
	1,  // 22: pb.ValidateContractRequest.manifest:type_name -> pb.ContractManifest
	25, // 23: pb.ValidateContractResponse.errors:type_name -> pb.ValidateContractResponse.ValidationError
	9,  // 24: pb.RevertContractResponse.revert_diff:type_name -> pb.ContractDiff
	1,  // 25: pb.GetContractTemplateResponse.template:type_name -> pb.ContractManifest
	2,  // 26: pb.ContractDiff.ResourceChange.resource:type_name -> pb.ResourceDefinition
	3,  // 27: pb.ContractDiff.ActionChange.action:type_name -> pb.ActionDefinition
	4,  // 28: pb.ContractDiff.RoleChange.role:type_name -> pb.RoleTemplate
	6,  // 29: pb.ContractDiff.BindingChange.binding:type_name -> pb.DefaultBinding
	7,  // 30: pb.ContractService.ApplyContract:input_type -> pb.ApplyContractRequest
	10, // 31: pb.ContractService.GetContract:input_type -> pb.GetContractRequest
	12, // 32: pb.ContractService.ListContracts:input_type -> pb.ListContractsRequest
	14, // 33: pb.ContractService.ValidateContract:input_type -> pb.ValidateContractRequest
	16, // 34: pb.ContractService.RevertContract:input_type -> pb.RevertContractRequest
	18, // 35: pb.ContractService.GetContractTemplate:input_type -> pb.GetContractTemplateRequest
	8,  // 36: pb.ContractService.ApplyContract:output_type -> pb.ApplyContractResponse
	11, // 37: pb.ContractService.GetContract:output_type -> pb.GetContractResponse
	13, // 38: pb.ContractService.ListContracts:output_type -> pb.ListContractsResponse
	15, // 39: pb.ContractService.ValidateContract:output_type -> pb.ValidateContractResponse
	17, // 40: pb.ContractService.RevertContract:output_type -> pb.RevertContractResponse
	19, // 41: pb.ContractService.GetContractTemplate:output_type -> pb.GetContractTemplateResponse
	36, // [36:42] is the sub-list for method output_type
	30, // [30:36] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_contract_proto_init() }
func file_contract_proto_init() {
	if File_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_proto_goTypes,
		DependencyIndexes: file_contract_proto_depIdxs,
		MessageInfos:      file_contract_proto_msgTypes,
	}.Build()
	File_contract_proto = out.File
	file_contract_proto_goTypes = nil
	file_contract_proto_depIdxs = nil
}
